---
title: "Track_Model"
author: "AT"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyr)
library(plyr)
library(dplyr)
require(tidyr)
require(dplyr)
require(ggplot2)
```

## Data In

Readin in data and preparing data frames

```{r cars}

# test_det <- read.csv("./input/testing.csv",sep = ",",header = TRUE)
getwd()
 train_data <- readRDS("../input/train_data.RDS")
 test_data <- readRDS("../input/test_data.RDS")

train_data <- train_data %>% group_by(ExperimentID) %>% mutate(lp = cumsum(Track))

train_data$lp <- train_data$lp/train_data$Track

train <- train_data %>% gather(acc, reading, -State, -ExperimentID, -Track, -Speed, -Payload,-lp )

test_data <- test_data %>% 
  group_by(ExperimentID) %>% mutate(lp = cumsum(Track))

test_data$lp <- test_data$lp/test_data$Track


 normalize <-readRDS("../input/test_offset_correlations.RDS")
getwd()
fit_all <- readRDS("../input/fit_all.RDS")
test_fit <- readRDS("../input/test_fit.RDS")
 
 # 
norm <- summarize(group_by(normalize,ExID, vars),
                  max_off=max(offset),mean_off=mean(offset),
                  min_off=min(offset),
                  med_off=median(offset))

# # list1 <- norm %>% 
#   filter(max_off != min_off) %>% 
#   group_by(ExID) %>% 
#   summarize(count = sum(ExID > 0),
#             off = median(med_off))

list2 <- norm %>%
  group_by(ExID) %>%
  summarize(off=median(med_off))

# list2 <- test_offsets[,-2]
names(list2) <- c("ExID", "off")
    
test_data <- merge(test_data,list2,by.x="ExperimentID",by.y = "ExID")

#rm(train_off)
# test_off <- merge(test,list1,by.x="ExperimentID",by.y="ExID")

# list1 <- merge(list1,test_det,by.x = "ExID", by.y = "ExperimentID")

test <- test_data %>% gather(acc, reading, -State, -ExperimentID, -Track, -Speed, -Payload,-lp, -off)

test$lp_off <- test$lp + test$off - 1



```

```{r}
param = "az_3r_2"

id = 1
p <- train %>%
  filter(acc == param &
           lp > (list2$off[id] - 1)  &
           lp < (list2$off[id] + 50) &
           Track == 1 ) %>%
  ggplot(.)+
  geom_point(aes(x=lp,y=reading,color=Payload))

p + test %>% filter(acc == param & ExperimentID == list2$ExID[id]) %>%
  geom_point(data=.,aes(x=lp_off,y=reading),color="red",shape=4,size=4)+
  labs(title=param)

```

## Track Model All

First Track Model - for all parameters  

```{r TrackModel1}

train$Payload2 <- train$Payload * train$Payload
train$Payload2 <- train$Payload * train$Payload

train$Speed2 <- train$Speed * train$Speed
test$Speed2 <- test$Speed * test$Speed

train$Speed_f <- as.factor(train$Speed)

test$Speed_f <- as.factor(test$Speed)

fit_all_light <- train %>% 
  group_by(Track, lp, acc) %>%
  do(fit11 = stripGlmLR(lm(reading ~ Payload + Payload2 + Speed , data = .)))

saveRDS(fit_all,file="fit_all.RDS")
#need to add offsets 
# rm(test_w_fits)
# test_w_fits <- merge(test,fit_all, 
#               by.x=c("lp_off","Track","acc"), 
#               by.y=c("lp","Track","acc"), 
#               all.x = TRUE)
# 
# 
# train_w_fits <- merge(train,fit_all, 
#               by.x=c("lp","Track","acc"), 
#               by.y=c("lp","Track","acc"), 
#               all.x = TRUE)

 predict(fit_all$fit11[[1]], test[1:5,])    

test_w_pred <- test[1,] %>% do(data.frame(param = .$acc,
                                             value = .$reading,
                                             num =  .$lp,
                                             Tr = .$Track,
                                             Speed = .$Speed,
                                             Payload = .$Payload,
                                             Payload2 = .$Payload2,
                                             pred <- predict(fit_all %>% 
                                                                 filter(Track == .$Track &
                                                                        lp == .$lp &
                                                                        acc == .$acc) %>% 
                                                                 select("fit11"),
                                                             newdata = .)
                                             ))


test_fit <- ddply(
    test,
    .(ExperimentID, lp_off, acc),
    .fun = function(df) {
    exptd_reading <- predict(fit_all_light[fit_all_light$ExperimentID == df$ExperimentID &
    fit_all_light$lp == df$lp_off &
    fit_all_light$acc == df$acc, ]$fit11[[1]],
    newdata = df)
    },
    .progress = progress_text(style = 3)
    )
    
# names(test_fit)[4] <- "exptd_reading"
saveRDS(test_fit, "../input/test_fit.RDS")

getModelSize(ttp)

train_fit <- ddply(
    train,
    .(Track, lp, acc),
    .fun = function(df) {
        exptd_reading <- predict(fit_all_light[fit_all_light$Track == max(df$Track) &
        fit_all_light$lp == max(df$lp) &
        fit_all_light$acc == max(df$acc),]$fit11[[1]],
        newdata = df)
    },
    # .parallel = TRUE,
.progress = progress_text(style = 3)
)

gc()
rm(fit_all)
ttp  <- fit_all[fit_all$Track == 1 &
        fit_all$lp == 1 &
        fit_all$acc == param,]$fit11[[1]]

ttpp <- stripGlmLR(ttp)
ttp <-  fit_all %>%   filter(Track == 1 &
lp == 1 &
acc == param) %>%
select(fit11[[1]])

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r Track & model vis prep}


az_pairs <-    cbind(
test_fit %>% slice(grep("^az_", acc, invert = FALSE)) %>% select(acc) %>% distinct(),
test_fit %>% slice(grep("^azp_", acc, invert = FALSE)) %>% select(acc) %>% distinct()
)
names(az_pairs) <- c("p_l", "p_h")

gains_test_fit <- ddply(.data = az_pairs , .(p_l) , .fun = function(df){
    # paste(max(df$p_l) , df$p_h)
            gain_calc(par_l = paste(df$p_l) , par_h = paste(df$p_h))
    }
            )

gains_test <- ddply(.data = az_pairs , .(p_l) , .fun = function(df){
    # paste(max(df$p_l) , df$p_h)
            gain_calc(df = test, par_l = paste(df$p_l) , par_h = paste(df$p_h),
                      val_var = "reading")
    }
            )

names(gains_test)
names(gains_test_fit)

gains_test_all <- left_join(gains_test_fit, 
                            gains_test %>% select(one_of(names(gains_test_fit)[-1])),
                                                      by = c("ExperimentID" = "ExperimentID",
                                                             "lp_off" = "lp_off",
                                                             "gain_func" = "gain_func"))
names(gains_test_all)
# 
# gain.x - expexted fit 
# gain.y - real data
gains_test_all <- gains_test_all %>% mutate(residuals_gain = gain.y - gain.x )

gains_test_sum <- gains_test_all %>%
    select(1:2, one_of("gain_func", "residuals_gain")) %>%
    group_by(ExperimentID, p_l, gain_func) %>%
    summarize(sum_res_gain = sum(residuals_gain),
              res_gain_sd = sd(residuals_gain),
            q25 = quantile(residuals_gain, probs=0.25),
            q50 = quantile(residuals_gain, probs=0.5),
            q75 = quantile(residuals_gain, probs=0.75)
            
              
) %>% ungroup() %>% mutate(part = substr(p_l,1,5))
# names(gains_test_sum)[6:8] <- c("q25","q50","q75")
```

```{r Track & model vis gain}
EID = 4

p <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y = gain.y  
                   
                  
    )) +
    geom_line(aes(color =  gain_func) ) 

show(p)

EID = 3
pp <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y = gain.y 
                  
                  
    )) +
    geom_line(aes(color =  gain_func) ) 
show(pp)

EID = 5

ppp <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y = gain.y  
                   
                  
    )) +
    geom_line(aes(color =  gain_func) ) 

show(ppp)


EID = 9

pppp <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y = gain.y  
                   
                  
    )) +
    geom_line(aes(color =  gain_func) ) 

show(pppp)

EID = 10

ppppp <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y = gain.y  
                   
                  
    )) +
    geom_line(aes(color =  gain_func) ) 

show(ppppp)
```


```{r Track & model vis gain model }
EID = 4

p <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y =  gain.x 
                   
                  
    )) +
    geom_line(aes(color =  gain_func) ) 

show(p)

EID = 3
pp <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y =  gain.x
                  
                  
    )) +
    geom_line(aes(color =  gain_func) ) 
show(pp)

EID = 5

ppp <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y =  gain.x 
                   
                  
    )) +
    geom_line(aes(color =  gain_func) ) 

show(ppp)


EID = 9

pppp <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y =  gain.x 
                   
                  
    )) +
    geom_line(aes(color =  gain_func) ) 

show(pppp)

EID = 107

ppppp <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y =  gain.x 
                   
                  
    )) +
    geom_line(aes(color =  gain_func) ) 

show(ppppp)
```

```{r Track & model vis }
EID = 4

p <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y = gain.y - gain.x 
                   
                  
    )) +
    geom_line(aes(color =  gain_func) ) 

show(p)

EID = 3
pp <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y = gain.y - gain.x
                  
                  
    )) +
    geom_line(aes(color =  gain_func) ) 
show(pp)

EID = 5

ppp <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y = gain.y - gain.x 
                   
                  
    )) +
    geom_line(aes(color =  gain_func) ) 

show(ppp)


EID = 9

pppp <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y = gain.y - gain.x 
                   
                  
    )) +
    geom_line(aes(color =  gain_func) ) 

show(pppp)

EID = 107

ppppp <- gains_test_all  %>% filter(ExperimentID == EID) %>%
    ggplot(., aes(x = lp_off,
                  y = gain.y - gain.x 
                   
                  
    )) +
    geom_line(aes(color =  gain_func) ) 

show(ppppp)
```
```{r Model summary vizualization}
names(gains_test_sum )
ps <- gains_test_sum   %>% filter(ExperimentID == 4) %>%
    ggplot(., aes(x = p_l,
                  y = sum_res_gain
                  
                  
    )) +
    geom_point(aes(color =  ExperimentID) ) 
show(ps)

ps <- gains_test_sum   %>% filter(ExperimentID == 3) %>%
    ggplot(., aes(x = p_l,
                  y = sum_res_gain
                  
                  
    )) +
    geom_point(aes(color =  ExperimentID) ) 
show(ps)

ps <- gains_test_sum   %>% filter(ExperimentID == 5) %>%
    ggplot(., aes(x = p_l,
                  y = sum_res_gain
                  
                  
    )) +
    geom_point(aes(color =  ExperimentID) ) 
show(ps)

ps <- gains_test_sum   %>% filter(ExperimentID == 9) %>%
    ggplot(., aes(x = p_l,
                  y = sum_res_gain
                  
                  
    )) +
    geom_point(aes(color =  ExperimentID) ) 
show(ps)

ps <- gains_test_sum   %>% filter(ExperimentID == 107) %>%
    ggplot(., aes(x = p_l,
                  y = sum_res_gain
                  
                  
    )) +
    geom_point(aes(color =  ExperimentID) ) 
show(ps)


```

```{r}
EID = 101

pa <- gains_test_all  %>% filter(ExperimentID == EID , grepl('az_2l*', p_l)) %>%
    
    ggplot(., aes(x = lp_off,
                  y = gain.y - gain.x 
                   
                  
    )) +
    geom_line(aes(color =  gain_func) ) 

show(pa)


gains_test_sum  %>%  filter(ExperimentID <= 200, q75 > 0.5 ) %>% select(ExperimentID) %>% distinct()

ps <- gains_test_sum  %>%  filter(ExperimentID <= 200, q75 > 0.5 ) %>%
    ggplot(., aes(x = part,
                  y = q75
                  
                  
    )) +
    geom_point(aes(color =  as.factor(ExperimentID))) 
show(ps)


ps <- gains_test_sum  %>%  filter(ExperimentID <= 200, q75 > 0.5 ) %>%
    ggplot(., aes(x = part,
                  y = q50
                  
                  
    )) +
    geom_point(aes(color =  as.factor(ExperimentID))) 
show(ps)



ps <- gains_test_sum  %>%  filter(ExperimentID <= 200, q50 > 0.15 ) %>% distinct()
    ggplot(., aes(x = part,
                  y = q50
                  
                  
    )) +
    geom_point(aes(color =  as.factor(ExperimentID))) 
show(ps)

psm <- gains_test_sum   %>% filter(ExperimentID <= 10, q25 < -0.4 ) %>%
    ggplot(., aes(x = part,
                  y = q25
                  
                  
    )) +
    geom_point(aes(color =  as.factor(ExperimentID)) ) 
show(psm)

```

```{r Secondary suspension}
#Naive classifier for dumpners

# 
# source(file = "./All_anomalies.R")

azs_par <- test_fit %>% slice(grep("^azs_", acc, invert = FALSE)) %>% select(acc) %>% distinct()

sec_res <- ddply(.data = azs_par , .(acc) , .fun = function(df){
    sensor_res(par = df$acc)})

```

```{r Secondary susp plots}

# sec_res.long <- melt(sec_res, id = "ExperimentID", measure = c("disp", "hp", "wt"))
# ggplot(sec_res.long , aes(sec_res, value, colour = variable)) + geom_line()

# known secondary spring failure
EID = 168
acc_v = "azs_1_1"
    
p <- sec_res  %>% filter(ExperimentID == EID)  %>% 
    slice(grep("^azs_1", acc, invert = FALSE)) %>%
    ggplot(., aes(x = lp_off)) +
    # geom_line(aes(y =  val_var_v.x, color =  paste("fit_var",acc)))  +
    # geom_line(aes(y =  val_var_v.y, color =  paste("real_val",acc)))  +
    geom_line(aes(y =  res_t_tf, color =  paste("res_val",acc)))

show(p)

EID = 1 # rather ok 
acc_v = "azs_1_1"
    
p <- sec_res  %>% filter(ExperimentID == EID)  %>% 
    slice(grep("^azs_", acc, invert = FALSE)) %>%
    ggplot(., aes(x = lp_off)) +
     # geom_line(aes(y =  val_var_v.x, color =  paste("fit_var",acc)))  +
     # geom_line(aes(y =  val_var_v.y, color =  paste("real_val",acc)))  +
    geom_line(aes(y =  res_t_tf, color =  paste("res_val",acc)))

show(p)


```

```{r over all review of second susp metrics}


ps <- sec_res_summ  %>% #  filter(q75 > 0.05 ) %>%
    ggplot(., aes(x = part,
                  y = q75
                  
                  
    )) +
    geom_boxplot()
    # geom_point(aes(color =  as.factor(ExperimentID))) 
show(ps)

outlier_values <- boxplot(part ~ q75, data = sec_res_summ)$out  # outlier values.
boxplot(sec_res_summ$q75, main="Pressure Height", boxwex=0.1)
mtext(paste("Outliers: ", paste(outlier_values, collapse=", ")), cex=0.6)

```

