---
title: "SystemModelv2"
author: "Antek"
date: "9 August 2017"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())

require(tidyr)
library(plyr)
library(dplyr)

require(dplyr)
require(ggplot2)

```

## Data in


```{r data in }

train_data <- readRDS("./input/train_data.RDS")
test_data <- readRDS("./input/test_data.RDS")
test_det <- read.csv("./input/testing.csv",sep = ",",header = TRUE)
normalize <-readRDS("./input/test_offset_correlations.RDS")

train_data <- train_data %>% group_by(ExperimentID) %>% mutate(lp = cumsum(Track))

train_data$lp <- train_data$lp/train_data$Track

test_data <- test_data %>% group_by(ExperimentID) %>% mutate(lp = cumsum(Track))

test_data$lp <- test_data$lp/test_data$Track



norm <- summarize(group_by(normalize,ExID, vars),
                  max_off=max(offset),mean_off=mean(offset),
                  min_off=min(offset),
                  med_off=median(offset))

list2 <- norm %>%
  group_by(ExID) %>%
  summarize(off=median(med_off))

#list2 <- merge(list2,test_det,by.x = "ExID", by.y = "ExperimentID")

test_data <- merge(test_data,list2,by.x="ExperimentID",by.y = "ExID")

#test <- test_data %>% gather(acc, reading, -State, -ExperimentID, -Track, -Speed, -Payload,-lp, -off)

test_data$lp_off <- test_data$lp + test_data$off- 1


```

## Variable prep

preparing sums of pairs to represent bogie motion  

```{r var prep}

train_data$Speed2 <- train_data$Speed**(2)
test_data$Speed2 <- train_data$Speed**(2)

# axis

train_data$azp_1_1 <- train_data$azp_1l_1 + train_data$azp_1r_1
train_data$azp_1_2 <- train_data$azp_1l_2 + train_data$azp_1r_2
train_data$azp_1_3 <- train_data$azp_1l_3 + train_data$azp_1r_3
train_data$azp_1_4 <- train_data$azp_1l_4 + train_data$azp_1r_4
train_data$azp_1_5 <- train_data$azp_1l_5 + train_data$azp_1r_5

train_data$azp_2_1 <- train_data$azp_2l_1 + train_data$azp_2r_1
train_data$azp_2_2 <- train_data$azp_2l_2 + train_data$azp_2r_2
train_data$azp_2_3 <- train_data$azp_2l_3 + train_data$azp_2r_3
train_data$azp_2_4 <- train_data$azp_2l_4 + train_data$azp_2r_4
train_data$azp_2_5 <- train_data$azp_2l_5 + train_data$azp_2r_5

train_data$azp_3_1 <- train_data$azp_3l_1 + train_data$azp_3r_1
train_data$azp_3_2 <- train_data$azp_3l_2 + train_data$azp_3r_2
train_data$azp_3_3 <- train_data$azp_3l_3 + train_data$azp_3r_3
train_data$azp_3_4 <- train_data$azp_3l_4 + train_data$azp_3r_4
train_data$azp_3_5 <- train_data$azp_3l_5 + train_data$azp_3r_5


train_data$azp_4_1 <- train_data$azp_4l_1 + train_data$azp_4r_1
train_data$azp_4_2 <- train_data$azp_4l_2 + train_data$azp_4r_2
train_data$azp_4_3 <- train_data$azp_4l_3 + train_data$azp_4r_3
train_data$azp_4_4 <- train_data$azp_4l_4 + train_data$azp_4r_4
train_data$azp_4_5 <- train_data$azp_4l_5 + train_data$azp_4r_5

# side to side

train_data$azp_fl_1 <- train_data$azp_1l_1 + train_data$azp_2l_1
train_data$azp_fl_2 <- train_data$azp_1l_2 + train_data$azp_2l_2
train_data$azp_fl_3 <- train_data$azp_1l_3 + train_data$azp_2l_3
train_data$azp_fl_4 <- train_data$azp_1l_4 + train_data$azp_2l_4
train_data$azp_fl_5 <- train_data$azp_1l_5 + train_data$azp_2l_5

train_data$azp_fr_1 <- train_data$azp_1r_1 + train_data$azp_2r_1
train_data$azp_fr_2 <- train_data$azp_1r_2 + train_data$azp_2r_2
train_data$azp_fr_3 <- train_data$azp_1r_3 + train_data$azp_2r_3
train_data$azp_fr_4 <- train_data$azp_1r_4 + train_data$azp_2r_4
train_data$azp_fr_5 <- train_data$azp_1r_5 + train_data$azp_2r_5

train_data$azp_rl_1 <- train_data$azp_3l_1 + train_data$azp_4l_1
train_data$azp_rl_2 <- train_data$azp_3l_2 + train_data$azp_4l_2
train_data$azp_rl_3 <- train_data$azp_3l_3 + train_data$azp_4l_3
train_data$azp_rl_4 <- train_data$azp_3l_4 + train_data$azp_4l_4
train_data$azp_rl_5 <- train_data$azp_3l_5 + train_data$azp_4l_5

train_data$azp_rr_1 <- train_data$azp_3r_1 + train_data$azp_4r_1
train_data$azp_rr_2 <- train_data$azp_3r_2 + train_data$azp_4r_2
train_data$azp_rr_3 <- train_data$azp_3r_3 + train_data$azp_4r_3
train_data$azp_rr_4 <- train_data$azp_3r_4 + train_data$azp_4r_4
train_data$azp_rr_5 <- train_data$azp_3r_5 + train_data$azp_4r_5

# TEST SET

test_data$azp_1_1 <- test_data$azp_1l_1 + test_data$azp_1r_1
test_data$azp_1_2 <- test_data$azp_1l_2 + test_data$azp_1r_2
test_data$azp_1_3 <- test_data$azp_1l_3 + test_data$azp_1r_3
test_data$azp_1_4 <- test_data$azp_1l_4 + test_data$azp_1r_4
test_data$azp_1_5 <- test_data$azp_1l_5 + test_data$azp_1r_5

test_data$azp_2_1 <- test_data$azp_2l_1 + test_data$azp_2r_1
test_data$azp_2_2 <- test_data$azp_2l_2 + test_data$azp_2r_2
test_data$azp_2_3 <- test_data$azp_2l_3 + test_data$azp_2r_3
test_data$azp_2_4 <- test_data$azp_2l_4 + test_data$azp_2r_4
test_data$azp_2_5 <- test_data$azp_2l_5 + test_data$azp_2r_5

test_data$azp_3_1 <- test_data$azp_3l_1 + test_data$azp_3r_1
test_data$azp_3_2 <- test_data$azp_3l_2 + test_data$azp_3r_2
test_data$azp_3_3 <- test_data$azp_3l_3 + test_data$azp_3r_3
test_data$azp_3_4 <- test_data$azp_3l_4 + test_data$azp_3r_4
test_data$azp_3_5 <- test_data$azp_3l_5 + test_data$azp_3r_5


test_data$azp_4_1 <- test_data$azp_4l_1 + test_data$azp_4r_1
test_data$azp_4_2 <- test_data$azp_4l_2 + test_data$azp_4r_2
test_data$azp_4_3 <- test_data$azp_4l_3 + test_data$azp_4r_3
test_data$azp_4_4 <- test_data$azp_4l_4 + test_data$azp_4r_4
test_data$azp_4_5 <- test_data$azp_4l_5 + test_data$azp_4r_5

# side to side

test_data$azp_fl_1 <- test_data$azp_1l_1 + test_data$azp_2l_1
test_data$azp_fl_2 <- test_data$azp_1l_2 + test_data$azp_2l_2
test_data$azp_fl_3 <- test_data$azp_1l_3 + test_data$azp_2l_3
test_data$azp_fl_4 <- test_data$azp_1l_4 + test_data$azp_2l_4
test_data$azp_fl_5 <- test_data$azp_1l_5 + test_data$azp_2l_5

test_data$azp_fr_1 <- test_data$azp_1r_1 + test_data$azp_2r_1
test_data$azp_fr_2 <- test_data$azp_1r_2 + test_data$azp_2r_2
test_data$azp_fr_3 <- test_data$azp_1r_3 + test_data$azp_2r_3
test_data$azp_fr_4 <- test_data$azp_1r_4 + test_data$azp_2r_4
test_data$azp_fr_5 <- test_data$azp_1r_5 + test_data$azp_2r_5

test_data$azp_rl_1 <- test_data$azp_3l_1 + test_data$azp_4l_1
test_data$azp_rl_2 <- test_data$azp_3l_2 + test_data$azp_4l_2
test_data$azp_rl_3 <- test_data$azp_3l_3 + test_data$azp_4l_3
test_data$azp_rl_4 <- test_data$azp_3l_4 + test_data$azp_4l_4
test_data$azp_rl_5 <- test_data$azp_3l_5 + test_data$azp_4l_5

test_data$azp_rr_1 <- test_data$azp_3r_1 + test_data$azp_4r_1
test_data$azp_rr_2 <- test_data$azp_3r_2 + test_data$azp_4r_2
test_data$azp_rr_3 <- test_data$azp_3r_3 + test_data$azp_4r_3
test_data$azp_rr_4 <- test_data$azp_3r_4 + test_data$azp_4r_4
test_data$azp_rr_5 <- test_data$azp_3r_5 + test_data$azp_4r_5



```
  
## motions approach  
  
```{r three motions approach}

## TRAIN DATA
# Z MOTION
# first bogie

train_data$b1z_1 <- train_data$azp_1_1 + train_data$azp_2_1
train_data$b1z_2 <- train_data$azp_1_2 + train_data$azp_2_2
train_data$b1z_3 <- train_data$azp_1_3 + train_data$azp_2_3
train_data$b1z_4 <- train_data$azp_1_4 + train_data$azp_2_4
train_data$b1z_5 <- train_data$azp_1_5 + train_data$azp_2_5

#wheels under first bogie

train_data$w1z_1 <- train_data$az_1l_1+train_data$az_1r_1+train_data$az_2l_1+train_data$az_2r_1
train_data$w1z_2 <- train_data$az_1l_2+train_data$az_1r_2+train_data$az_2l_2+train_data$az_2r_2
train_data$w1z_3 <- train_data$az_1l_3+train_data$az_1r_3+train_data$az_2l_3+train_data$az_2r_3
train_data$w1z_4 <- train_data$az_1l_4+train_data$az_1r_4+train_data$az_2l_4+train_data$az_2r_4
train_data$w1z_5 <- train_data$az_1l_5+train_data$az_1r_5+train_data$az_2l_5+train_data$az_2r_5

# second bogie

train_data$b2z_1 <- train_data$azp_3_1 + train_data$azp_4_1
train_data$b2z_2 <- train_data$azp_3_2 + train_data$azp_4_2
train_data$b2z_3 <- train_data$azp_3_3 + train_data$azp_4_3
train_data$b2z_4 <- train_data$azp_3_4 + train_data$azp_4_4
train_data$b2z_5 <- train_data$azp_3_5 + train_data$azp_4_5

#wheels under second bogie

train_data$w2z_1 <- train_data$az_3l_1+train_data$az_3r_1+train_data$az_4l_1+train_data$az_4r_1
train_data$w2z_2 <- train_data$az_3l_2+train_data$az_3r_2+train_data$az_4l_2+train_data$az_4r_2
train_data$w2z_3 <- train_data$az_3l_3+train_data$az_3r_3+train_data$az_4l_3+train_data$az_4r_3
train_data$w2z_4 <- train_data$az_3l_4+train_data$az_3r_4+train_data$az_4l_4+train_data$az_4r_4
train_data$w2z_5 <- train_data$az_3l_5+train_data$az_3r_5+train_data$az_4l_5+train_data$az_4r_5

#platform

train_data$pz_1 <- train_data$azs_1_1 + train_data$azs_2_1
train_data$pz_2 <- train_data$azs_1_2 + train_data$azs_2_2
train_data$pz_3 <- train_data$azs_1_3 + train_data$azs_2_3
train_data$pz_4 <- train_data$azs_1_4 + train_data$azs_2_4
train_data$pz_5 <- train_data$azs_1_5 + train_data$azs_2_5

# ROLL
# first bogie

train_data$b1r_1 <- 1.5*train_data$azp_fl_1 -0.5*train_data$azp_fr_1
train_data$b1r_2 <- 1.5*train_data$azp_fl_2 -0.5*train_data$azp_fr_2
train_data$b1r_3 <- 1.5*train_data$azp_fl_3 -0.5*train_data$azp_fr_3
train_data$b1r_4 <- 1.5*train_data$azp_fl_4 -0.5*train_data$azp_fr_4
train_data$b1r_5 <- 1.5*train_data$azp_fl_5 -0.5*train_data$azp_fr_5

#wheels under first bogie

train_data$w1r_1 <- 1.5*train_data$az_1l_1-0.5*train_data$az_1r_1+1.5*train_data$az_2l_1-0.5*train_data$az_2r_1
train_data$w1r_2 <- 1.5*train_data$az_1l_2-0.5*train_data$az_1r_2+1.5*train_data$az_2l_2-0.5*train_data$az_2r_2
train_data$w1r_3 <- 1.5*train_data$az_1l_3-0.5*train_data$az_1r_3+1.5*train_data$az_2l_3-0.5*train_data$az_2r_3
train_data$w1r_4 <- 1.5*train_data$az_1l_4-0.5*train_data$az_1r_4+1.5*train_data$az_2l_4-0.5*train_data$az_2r_4
train_data$w1r_5 <- 1.5*train_data$az_1l_5-0.5*train_data$az_1r_5+1.5*train_data$az_2l_5-0.5*train_data$az_2r_5

# second bogie

train_data$b2r_1 <- 1.5*train_data$azp_rl_1 -0.5*train_data$azp_rr_1
train_data$b2r_2 <- 1.5*train_data$azp_rl_2 -0.5*train_data$azp_rr_2
train_data$b2r_3 <- 1.5*train_data$azp_rl_3 -0.5*train_data$azp_rr_3
train_data$b2r_4 <- 1.5*train_data$azp_rl_4 -0.5*train_data$azp_rr_4
train_data$b2r_5 <- 1.5*train_data$azp_rl_5 -0.5*train_data$azp_rr_5

#wheels under second bogie

train_data$w2r_1 <- 1.5*train_data$az_3l_1-0.5*train_data$az_3r_1+1.5*train_data$az_4l_1-0.5*train_data$az_4r_1
train_data$w2r_2 <- 1.5*train_data$az_3l_2-0.5*train_data$az_3r_2+1.5*train_data$az_4l_2-0.5*train_data$az_4r_2
train_data$w2r_3 <- 1.5*train_data$az_3l_3-0.5*train_data$az_3r_3+1.5*train_data$az_4l_3-0.5*train_data$az_4r_3
train_data$w2r_4 <- 1.5*train_data$az_3l_4-0.5*train_data$az_3r_4+1.5*train_data$az_4l_4-0.5*train_data$az_4r_4
train_data$w2r_5 <- 1.5*train_data$az_3l_5-0.5*train_data$az_3r_5+1.5*train_data$az_4l_5-0.5*train_data$az_4r_5

#platform - no roll for platform...

# PITCH

# first bogie

train_data$b1p_1 <- 1.5*train_data$azp_1_1 -0.5*train_data$azp_2_1
train_data$b1p_2 <- 1.5*train_data$azp_1_2 -0.5*train_data$azp_2_2
train_data$b1p_3 <- 1.5*train_data$azp_1_3 -0.5*train_data$azp_2_3
train_data$b1p_4 <- 1.5*train_data$azp_1_4 -0.5*train_data$azp_2_4
train_data$b1p_5 <- 1.5*train_data$azp_1_5 -0.5*train_data$azp_2_5

#wheels under first bogie

train_data$w1p_1 <- 1.5*train_data$az_1l_1-0.5*train_data$az_2r_1+1.5*train_data$az_1l_1-0.5*train_data$az_2r_1
train_data$w1p_2 <- 1.5*train_data$az_1l_2-0.5*train_data$az_2r_2+1.5*train_data$az_1l_2-0.5*train_data$az_2r_2
train_data$w1p_3 <- 1.5*train_data$az_1l_3-0.5*train_data$az_2r_3+1.5*train_data$az_1l_3-0.5*train_data$az_2r_3
train_data$w1p_4 <- 1.5*train_data$az_1l_4-0.5*train_data$az_2r_4+1.5*train_data$az_1l_4-0.5*train_data$az_2r_4
train_data$w1p_5 <- 1.5*train_data$az_1l_5-0.5*train_data$az_2r_5+1.5*train_data$az_1l_5-0.5*train_data$az_2r_5

# second bogie

train_data$b2p_1 <- 1.5*train_data$azp_3_1 -0.5*train_data$azp_4_1
train_data$b2p_2 <- 1.5*train_data$azp_3_2 -0.5*train_data$azp_4_2
train_data$b2p_3 <- 1.5*train_data$azp_3_3 -0.5*train_data$azp_4_3
train_data$b2p_4 <- 1.5*train_data$azp_3_4 -0.5*train_data$azp_4_4
train_data$b2p_5 <- 1.5*train_data$azp_3_5 -0.5*train_data$azp_4_5

#wheels under second bogie

train_data$w2p_1 <- 1.5*train_data$az_3l_1-0.5*train_data$az_4r_1+1.5*train_data$az_3l_1-0.5*train_data$az_4r_1
train_data$w2p_2 <- 1.5*train_data$az_3l_2-0.5*train_data$az_4r_2+1.5*train_data$az_3l_2-0.5*train_data$az_4r_2
train_data$w2p_3 <- 1.5*train_data$az_3l_3-0.5*train_data$az_4r_3+1.5*train_data$az_3l_3-0.5*train_data$az_4r_3
train_data$w2p_4 <- 1.5*train_data$az_3l_4-0.5*train_data$az_4r_4+1.5*train_data$az_3l_4-0.5*train_data$az_4r_4
train_data$w2p_5 <- 1.5*train_data$az_3l_5-0.5*train_data$az_4r_5+1.5*train_data$az_3l_5-0.5*train_data$az_4r_5

#platform

train_data$pp_1 <- 1.5*train_data$azs_1_1 -0.5*train_data$azs_2_1
train_data$pp_2 <- 1.5*train_data$azs_1_2 -0.5*train_data$azs_2_2
train_data$pp_3 <- 1.5*train_data$azs_1_3 -0.5*train_data$azs_2_3
train_data$pp_4 <- 1.5*train_data$azs_1_4 -0.5*train_data$azs_2_4
train_data$pp_5 <- 1.5*train_data$azs_1_5 -0.5*train_data$azs_2_5



## test DATA
# Z MOTION
# first bogie

test_data$b1z_1 <- test_data$azp_1_1 + test_data$azp_2_1
test_data$b1z_2 <- test_data$azp_1_2 + test_data$azp_2_2
test_data$b1z_3 <- test_data$azp_1_3 + test_data$azp_2_3
test_data$b1z_4 <- test_data$azp_1_4 + test_data$azp_2_4
test_data$b1z_5 <- test_data$azp_1_5 + test_data$azp_2_5

#wheels uner first bogie

test_data$w1z_1 <- test_data$az_1l_1+test_data$az_1r_1+test_data$az_2l_1+test_data$az_2r_1
test_data$w1z_2 <- test_data$az_1l_2+test_data$az_1r_2+test_data$az_2l_2+test_data$az_2r_2
test_data$w1z_3 <- test_data$az_1l_3+test_data$az_1r_3+test_data$az_2l_3+test_data$az_2r_3
test_data$w1z_4 <- test_data$az_1l_4+test_data$az_1r_4+test_data$az_2l_4+test_data$az_2r_4
test_data$w1z_5 <- test_data$az_1l_5+test_data$az_1r_5+test_data$az_2l_5+test_data$az_2r_5

# secondbogie

test_data$b2z_1 <- test_data$azp_3_1 + test_data$azp_4_1
test_data$b2z_2 <- test_data$azp_3_2 + test_data$azp_4_2
test_data$b2z_3 <- test_data$azp_3_3 + test_data$azp_4_3
test_data$b2z_4 <- test_data$azp_3_4 + test_data$azp_4_4
test_data$b2z_5 <- test_data$azp_3_5 + test_data$azp_4_5

#wheels uner first bogie

test_data$w2z_1 <- test_data$az_3l_1+test_data$az_3r_1+test_data$az_4l_1+test_data$az_4r_1
test_data$w2z_2 <- test_data$az_3l_2+test_data$az_3r_2+test_data$az_4l_2+test_data$az_4r_2
test_data$w2z_3 <- test_data$az_3l_3+test_data$az_3r_3+test_data$az_4l_3+test_data$az_4r_3
test_data$w2z_4 <- test_data$az_3l_4+test_data$az_3r_4+test_data$az_4l_4+test_data$az_4r_4
test_data$w2z_5 <- test_data$az_3l_5+test_data$az_3r_5+test_data$az_4l_5+test_data$az_4r_5

#platform

test_data$pz_1 <- test_data$azs_1_1 + test_data$azs_2_1
test_data$pz_2 <- test_data$azs_1_2 + test_data$azs_2_2
test_data$pz_3 <- test_data$azs_1_3 + test_data$azs_2_3
test_data$pz_4 <- test_data$azs_1_4 + test_data$azs_2_4
test_data$pz_5 <- test_data$azs_1_5 + test_data$azs_2_5

# ROLL
# first bogie

test_data$b1r_1 <- 1.5*test_data$azp_fl_1 -0.5*test_data$azp_fr_1
test_data$b1r_2 <- 1.5*test_data$azp_fl_2 -0.5*test_data$azp_fr_2
test_data$b1r_3 <- 1.5*test_data$azp_fl_3 -0.5*test_data$azp_fr_3
test_data$b1r_4 <- 1.5*test_data$azp_fl_4 -0.5*test_data$azp_fr_4
test_data$b1r_5 <- 1.5*test_data$azp_fl_5 -0.5*test_data$azp_fr_5

#wheels uner first bogie

test_data$w1r_1 <- 1.5*test_data$az_1l_1-0.5*test_data$az_1r_1+1.5*test_data$az_2l_1-0.5*test_data$az_2r_1
test_data$w1r_2 <- 1.5*test_data$az_1l_2-0.5*test_data$az_1r_2+1.5*test_data$az_2l_2-0.5*test_data$az_2r_2
test_data$w1r_3 <- 1.5*test_data$az_1l_3-0.5*test_data$az_1r_3+1.5*test_data$az_2l_3-0.5*test_data$az_2r_3
test_data$w1r_4 <- 1.5*test_data$az_1l_4-0.5*test_data$az_1r_4+1.5*test_data$az_2l_4-0.5*test_data$az_2r_4
test_data$w1r_5 <- 1.5*test_data$az_1l_5-0.5*test_data$az_1r_5+1.5*test_data$az_2l_5-0.5*test_data$az_2r_5

# second bogie

test_data$b2r_1 <- 1.5*test_data$azp_rl_1 -0.5*test_data$azp_rr_1
test_data$b2r_2 <- 1.5*test_data$azp_rl_2 -0.5*test_data$azp_rr_2
test_data$b2r_3 <- 1.5*test_data$azp_rl_3 -0.5*test_data$azp_rr_3
test_data$b2r_4 <- 1.5*test_data$azp_rl_4 -0.5*test_data$azp_rr_4
test_data$b2r_5 <- 1.5*test_data$azp_rl_5 -0.5*test_data$azp_rr_5

#wheels uner first bogie

test_data$w2r_1 <- 1.5*test_data$az_3l_1-0.5*test_data$az_3r_1+1.5*test_data$az_4l_1-0.5*test_data$az_4r_1
test_data$w2r_2 <- 1.5*test_data$az_3l_2-0.5*test_data$az_3r_2+1.5*test_data$az_4l_2-0.5*test_data$az_4r_2
test_data$w2r_3 <- 1.5*test_data$az_3l_3-0.5*test_data$az_3r_3+1.5*test_data$az_4l_3-0.5*test_data$az_4r_3
test_data$w2r_4 <- 1.5*test_data$az_3l_4-0.5*test_data$az_3r_4+1.5*test_data$az_4l_4-0.5*test_data$az_4r_4
test_data$w2r_5 <- 1.5*test_data$az_3l_5-0.5*test_data$az_3r_5+1.5*test_data$az_4l_5-0.5*test_data$az_4r_5

#platform - no roll for platform...

# PITCH

# first bogie

test_data$b1p_1 <- 1.5*test_data$azp_1_1 -0.5*test_data$azp_2_1
test_data$b1p_2 <- 1.5*test_data$azp_1_2 -0.5*test_data$azp_2_2
test_data$b1p_3 <- 1.5*test_data$azp_1_3 -0.5*test_data$azp_2_3
test_data$b1p_4 <- 1.5*test_data$azp_1_4 -0.5*test_data$azp_2_4
test_data$b1p_5 <- 1.5*test_data$azp_1_5 -0.5*test_data$azp_2_5

#wheels uner first bogie

test_data$w1p_1 <- 1.5*test_data$az_1l_1-0.5*test_data$az_2r_1+1.5*test_data$az_1l_1-0.5*test_data$az_2r_1
test_data$w1p_2 <- 1.5*test_data$az_1l_2-0.5*test_data$az_2r_2+1.5*test_data$az_1l_2-0.5*test_data$az_2r_2
test_data$w1p_3 <- 1.5*test_data$az_1l_3-0.5*test_data$az_2r_3+1.5*test_data$az_1l_3-0.5*test_data$az_2r_3
test_data$w1p_4 <- 1.5*test_data$az_1l_4-0.5*test_data$az_2r_4+1.5*test_data$az_1l_4-0.5*test_data$az_2r_4
test_data$w1p_5 <- 1.5*test_data$az_1l_5-0.5*test_data$az_2r_5+1.5*test_data$az_1l_5-0.5*test_data$az_2r_5

# second bogie

test_data$b2p_1 <- 1.5*test_data$azp_3_1 -0.5*test_data$azp_4_1
test_data$b2p_2 <- 1.5*test_data$azp_3_2 -0.5*test_data$azp_4_2
test_data$b2p_3 <- 1.5*test_data$azp_3_3 -0.5*test_data$azp_4_3
test_data$b2p_4 <- 1.5*test_data$azp_3_4 -0.5*test_data$azp_4_4
test_data$b2p_5 <- 1.5*test_data$azp_3_5 -0.5*test_data$azp_4_5

#wheels uner first bogie

test_data$w2p_1 <- 1.5*test_data$az_3l_1-0.5*test_data$az_4r_1+1.5*test_data$az_3l_1-0.5*test_data$az_4r_1
test_data$w2p_2 <- 1.5*test_data$az_3l_2-0.5*test_data$az_4r_2+1.5*test_data$az_3l_2-0.5*test_data$az_4r_2
test_data$w2p_3 <- 1.5*test_data$az_3l_3-0.5*test_data$az_4r_3+1.5*test_data$az_3l_3-0.5*test_data$az_4r_3
test_data$w2p_4 <- 1.5*test_data$az_3l_4-0.5*test_data$az_4r_4+1.5*test_data$az_3l_4-0.5*test_data$az_4r_4
test_data$w2p_5 <- 1.5*test_data$az_3l_5-0.5*test_data$az_4r_5+1.5*test_data$az_3l_5-0.5*test_data$az_4r_5

#platform

test_data$pp_1 <- 1.5*test_data$azs_1_1 -0.5*test_data$azs_2_1
test_data$pp_2 <- 1.5*test_data$azs_1_2 -0.5*test_data$azs_2_2
test_data$pp_3 <- 1.5*test_data$azs_1_3 -0.5*test_data$azs_2_3
test_data$pp_4 <- 1.5*test_data$azs_1_4 -0.5*test_data$azs_2_4
test_data$pp_5 <- 1.5*test_data$azs_1_5 -0.5*test_data$azs_2_5





```
  
## 3 motion plots  


```{r plots}

train_data %>%
  ggplot(.,aes(x=b1z_2-w1z_2,y=w1p_2,color=w1r_2))+
  geom_point()

train_data %>%
  ggplot(.,aes(x=w1z_3,y=b1z_3,color=w1r_3))+
  geom_point()

train_data %>%
  ggplot(.,aes(x=w1r_2,y=w1p_2,color=w1p_2))+
  geom_point(alpha=0.5)


train_data %>%
  ggplot(.,aes(x=1.5*b1z_2-0.5*b2z_2,y=pz_2, color = b1z_2+b2z_2))+
  geom_point(alpha=0.5)+
  facet_wrap(~Speed)

fit3z <- lm(formula = b1z_3 ~ w1z_3 + w1r_3 + w1p_3 +  Payload + Speed, data= train_data)

# fit1az <-

summary(fit3z)

train_data %>% lm(formula = b1z_3 ~ w1z_3 +  Payload + Speed, data=.) %>% summary()

train_data %>% lm(formula = b1r_3 ~ w1r_3 + w1z_3 + w1p_3 +  Payload + Speed, data=.) %>% summary()

train_data %>% lm(formula = b1p_3 ~ w1p_3 + w1z_3 + w1r_3 +  Payload + Speed, data=.) %>% summary()

train_data %>% lm(formula = pz_2 ~ b1z_2 + b2z_2 +  Payload + Speed, data=.) %>% summary()

train_data %>% lm(formula = pp_1 ~ b1z_2 + b2z_1 + b1p_1 + b2p_1 +  Payload + Speed, data=.) %>% summary()

train_data %>% lm(formula = pz_1 ~ b1z_1 + b2z_1 + b1p_1 + b2p_1 +  Payload + Speed, data=.) %>% summary()


train_data %>% lm(formula = azs_1_1 ~ b1z_1 + b1p_1 + b1r_1 + +  Payload + Speed + azs_2_1, data=.) %>% summary()
train_data %>% lm(formula = azs_1_2 ~ b1z_2 + b1p_2 + b1r_2 + +  Payload + Speed + azs_2_2, data=.) %>% summary()

train_data %>% lm(formula = azs_2_2 ~ b2z_2 + b2p_2 + b2r_2 + Payload, data=.) %>% summary()


fit4z <- lm(formula = b1z_4 ~ w1z_4 + w1r_4 + w1p_4 +  Payload + Speed, data= train_data)
summary(fit4z)

fit4z_test <- lm(formula = b1z_4 ~ w1z_4 + w1r_4 + w1p_4 +  Payload + Speed, data= test_data)
summary(fit4z_test)

    lm(formula = az_1l_1 ~ az_1r_1 + az_2r_1 + az_3r_1 + az_4r_1 +
        az_2l_1 + az_3l_1 + az_4l_1 + Payload + Speed, data= train_data)%>% summary()



```
## fits for motion model - Bogie

```{r motion fits With Payload & Speed}

# b1z

fit_b1z_1 <- lm(formula = b1z_1 ~ w1z_1 + w1r_1 + w1p_1 + Payload + Speed, data= train_data)
fit_b1z_2 <- lm(formula = b1z_2 ~ w1z_2 + w1r_2 + w1p_2 + Payload + Speed, data= train_data)
fit_b1z_3 <- lm(formula = b1z_3 ~ w1z_3 + w1r_3 + w1p_3 + Payload + Speed, data= train_data)
fit_b1z_4 <- lm(formula = b1z_4 ~ w1z_4 + w1r_4 + w1p_4 + Payload + Speed, data= train_data)
fit_b1z_5 <- lm(formula = b1z_5 ~ w1z_5 + w1r_5 + w1p_5 + Payload + Speed, data= train_data)

test_data$b1z_1_pred <- predict.lm(fit_b1z_1,newdata = test_data)
test_data$b1z_2_pred <- predict.lm(fit_b1z_2,newdata = test_data)
test_data$b1z_3_pred <- predict.lm(fit_b1z_3,newdata = test_data)
test_data$b1z_4_pred <- predict.lm(fit_b1z_4,newdata = test_data)
test_data$b1z_5_pred <- predict.lm(fit_b1z_5,newdata = test_data)


# b1r

fit_b1r_1 <- lm(formula = b1r_1 ~ w1z_1 + w1r_1 + w1p_1 + Payload + Speed, data= train_data)
fit_b1r_2 <- lm(formula = b1r_2 ~ w1z_2 + w1r_2 + w1p_2 + Payload + Speed, data= train_data)
fit_b1r_3 <- lm(formula = b1r_3 ~ w1z_3 + w1r_3 + w1p_3 + Payload + Speed, data= train_data)
fit_b1r_4 <- lm(formula = b1r_4 ~ w1z_4 + w1r_4 + w1p_4 + Payload + Speed, data= train_data)
fit_b1r_5 <- lm(formula = b1r_5 ~ w1z_5 + w1r_5 + w1p_5 + Payload + Speed, data= train_data)

test_data$b1r_1_pred <- predict.lm(fit_b1r_1,newdata = test_data)
test_data$b1r_2_pred <- predict.lm(fit_b1r_2,newdata = test_data)
test_data$b1r_3_pred <- predict.lm(fit_b1r_3,newdata = test_data)
test_data$b1r_4_pred <- predict.lm(fit_b1r_4,newdata = test_data)
test_data$b1r_5_pred <- predict.lm(fit_b1r_5,newdata = test_data)

# b1p

fit_b1p_1 <- lm(formula = b1p_1 ~ w1z_1 + w1r_1 + w1p_1 + Payload + Speed, data= train_data)
fit_b1p_2 <- lm(formula = b1p_2 ~ w1z_2 + w1r_2 + w1p_2 + Payload + Speed, data= train_data)
fit_b1p_3 <- lm(formula = b1p_3 ~ w1z_3 + w1r_3 + w1p_3 + Payload + Speed, data= train_data)
fit_b1p_4 <- lm(formula = b1p_4 ~ w1z_4 + w1r_4 + w1p_4 + Payload + Speed, data= train_data)
fit_b1p_5 <- lm(formula = b1p_5 ~ w1z_5 + w1r_5 + w1p_5 + Payload + Speed, data= train_data)

test_data$b1p_1_pred <- predict.lm(fit_b1p_1,newdata = test_data)
test_data$b1p_2_pred <- predict.lm(fit_b1p_2,newdata = test_data)
test_data$b1p_3_pred <- predict.lm(fit_b1p_3,newdata = test_data)
test_data$b1p_4_pred <- predict.lm(fit_b1p_4,newdata = test_data)
test_data$b1p_5_pred <- predict.lm(fit_b1p_5,newdata = test_data)

#b2z

fit_b2z_1 <- lm(formula = b2z_1 ~ w2z_1 + w2r_1 + w2p_1 + Payload + Speed, data= train_data)
fit_b2z_2 <- lm(formula = b2z_2 ~ w2z_2 + w2r_2 + w2p_2 + Payload + Speed, data= train_data)
fit_b2z_3 <- lm(formula = b2z_3 ~ w2z_3 + w2r_3 + w2p_3 + Payload + Speed, data= train_data)
fit_b2z_4 <- lm(formula = b2z_4 ~ w2z_4 + w2r_4 + w2p_4 + Payload + Speed, data= train_data)
fit_b2z_5 <- lm(formula = b2z_5 ~ w2z_5 + w2r_5 + w2p_5 + Payload + Speed, data= train_data)

test_data$b2z_1_pred <- predict.lm(fit_b2z_1,newdata = test_data)
test_data$b2z_2_pred <- predict.lm(fit_b2z_2,newdata = test_data)
test_data$b2z_3_pred <- predict.lm(fit_b2z_3,newdata = test_data)
test_data$b2z_4_pred <- predict.lm(fit_b2z_4,newdata = test_data)
test_data$b2z_5_pred <- predict.lm(fit_b2z_5,newdata = test_data)

# b2r

fit_b2r_1 <- lm(formula = b2r_1 ~ w2z_1 + w2r_1 + w2p_1 + Payload + Speed, data= train_data)
fit_b2r_2 <- lm(formula = b2r_2 ~ w2z_2 + w2r_2 + w2p_2 + Payload + Speed, data= train_data)
fit_b2r_3 <- lm(formula = b2r_3 ~ w2z_3 + w2r_3 + w2p_3 + Payload + Speed, data= train_data)
fit_b2r_4 <- lm(formula = b2r_4 ~ w2z_4 + w2r_4 + w2p_4 + Payload + Speed, data= train_data)
fit_b2r_5 <- lm(formula = b2r_5 ~ w2z_5 + w2r_5 + w2p_5 + Payload + Speed, data= train_data)

test_data$b2r_1_pred <- predict.lm(fit_b2r_1,newdata = test_data)
test_data$b2r_2_pred <- predict.lm(fit_b2r_2,newdata = test_data)
test_data$b2r_3_pred <- predict.lm(fit_b2r_3,newdata = test_data)
test_data$b2r_4_pred <- predict.lm(fit_b2r_4,newdata = test_data)
test_data$b2r_5_pred <- predict.lm(fit_b2r_5,newdata = test_data)

# b2p

fit_b2p_1 <- lm(formula = b2p_1 ~ w2z_1 + w2r_1 + w2p_1 + Payload + Speed, data= train_data)
fit_b2p_2 <- lm(formula = b2p_2 ~ w2z_2 + w2r_2 + w2p_2 + Payload + Speed, data= train_data)
fit_b2p_3 <- lm(formula = b2p_3 ~ w2z_3 + w2r_3 + w2p_3 + Payload + Speed, data= train_data)
fit_b2p_4 <- lm(formula = b2p_4 ~ w2z_4 + w2r_4 + w2p_4 + Payload + Speed, data= train_data)
fit_b2p_5 <- lm(formula = b2p_5 ~ w2z_5 + w2r_5 + w2p_5 + Payload + Speed, data= train_data)

test_data$b2p_1_pred <- predict.lm(fit_b2p_1,newdata = test_data)
test_data$b2p_2_pred <- predict.lm(fit_b2p_2,newdata = test_data)
test_data$b2p_3_pred <- predict.lm(fit_b2p_3,newdata = test_data)
test_data$b2p_4_pred <- predict.lm(fit_b2p_4,newdata = test_data)
test_data$b2p_5_pred <- predict.lm(fit_b2p_5,newdata = test_data)

# calculating residuals

test_data$b1z_1_res <- test_data$b1z_1 - test_data$b1z_1_pred
test_data$b1z_2_res <- test_data$b1z_2 - test_data$b1z_2_pred
test_data$b1z_3_res <- test_data$b1z_3 - test_data$b1z_3_pred
test_data$b1z_4_res <- test_data$b1z_4 - test_data$b1z_4_pred
test_data$b1z_5_res <- test_data$b1z_5 - test_data$b1z_5_pred

test_data$b1r_1_res <- test_data$b1r_1 - test_data$b1r_1_pred
test_data$b1r_2_res <- test_data$b1r_2 - test_data$b1r_2_pred
test_data$b1r_3_res <- test_data$b1r_3 - test_data$b1r_3_pred
test_data$b1r_4_res <- test_data$b1r_4 - test_data$b1r_4_pred
test_data$b1r_5_res <- test_data$b1r_5 - test_data$b1r_5_pred

test_data$b1p_1_res <- test_data$b1p_1 - test_data$b1p_1_pred
test_data$b1p_2_res <- test_data$b1p_2 - test_data$b1p_2_pred
test_data$b1p_3_res <- test_data$b1p_3 - test_data$b1p_3_pred
test_data$b1p_4_res <- test_data$b1p_4 - test_data$b1p_4_pred
test_data$b1p_5_res <- test_data$b1p_5 - test_data$b1p_5_pred

# Bogie 2

test_data$b2z_1_res <- test_data$b2z_1 - test_data$b2z_1_pred
test_data$b2z_2_res <- test_data$b2z_2 - test_data$b2z_2_pred
test_data$b2z_3_res <- test_data$b2z_3 - test_data$b2z_3_pred
test_data$b2z_4_res <- test_data$b2z_4 - test_data$b2z_4_pred
test_data$b2z_5_res <- test_data$b2z_5 - test_data$b2z_5_pred

test_data$b2r_1_res <- test_data$b2r_1 - test_data$b2r_1_pred
test_data$b2r_2_res <- test_data$b2r_2 - test_data$b2r_2_pred
test_data$b2r_3_res <- test_data$b2r_3 - test_data$b2r_3_pred
test_data$b2r_4_res <- test_data$b2r_4 - test_data$b2r_4_pred
test_data$b2r_5_res <- test_data$b2r_5 - test_data$b2r_5_pred

test_data$b2p_1_res <- test_data$b2p_1 - test_data$b2p_1_pred
test_data$b2p_2_res <- test_data$b2p_2 - test_data$b2p_2_pred
test_data$b2p_3_res <- test_data$b2p_3 - test_data$b2p_3_pred
test_data$b2p_4_res <- test_data$b2p_4 - test_data$b2p_4_pred
test_data$b2p_5_res <- test_data$b2p_5 - test_data$b2p_5_pred

# Platform
# PZ
fit_pz_1 <- lm(formula = pz_1 ~ b1z_1 + b2z_1 + b1p_1 + b2p_1 +  Payload + Speed, data = train_data)
fit_pz_2 <- lm(formula = pz_2 ~ b1z_2 + b2z_2 + b1p_2 + b2p_2 +  Payload + Speed, data = train_data)
fit_pz_3 <- lm(formula = pz_3 ~ b1z_3 + b2z_3 + b1p_3 + b2p_3 +  Payload + Speed, data = train_data)
fit_pz_4 <- lm(formula = pz_4 ~ b1z_4 + b2z_4 + b1p_4 + b2p_4 +  Payload + Speed, data = train_data)
fit_pz_5 <- lm(formula = pz_5 ~ b1z_5 + b2z_5 + b1p_5 + b2p_5 +  Payload + Speed, data = train_data)

fit_pp_1 <- lm(formula = pp_1 ~ b1z_1 + b2z_1 + b1p_1 + b2p_1 +  Payload + Speed, data = train_data)
fit_pp_2 <- lm(formula = pp_2 ~ b1z_2 + b2z_2 + b1p_2 + b2p_2 +  Payload + Speed, data = train_data)
fit_pp_3 <- lm(formula = pp_3 ~ b1z_3 + b2z_3 + b1p_3 + b2p_3 +  Payload + Speed, data = train_data)
fit_pp_4 <- lm(formula = pp_4 ~ b1z_4 + b2z_4 + b1p_4 + b2p_4 +  Payload + Speed, data = train_data)
fit_pp_5 <- lm(formula = pp_5 ~ b1z_5 + b2z_5 + b1p_5 + b2p_5 +  Payload + Speed, data = train_data)

# predictions platform

test_data$pz_1_pred <- predict.lm(fit_pz_1,newdata = test_data)
test_data$pz_2_pred <- predict.lm(fit_pz_2,newdata = test_data)
test_data$pz_3_pred <- predict.lm(fit_pz_3,newdata = test_data)
test_data$pz_4_pred <- predict.lm(fit_pz_4,newdata = test_data)
test_data$pz_5_pred <- predict.lm(fit_pz_5,newdata = test_data)


test_data$pp_1_pred <- predict.lm(fit_pp_1,newdata = test_data)
test_data$pp_2_pred <- predict.lm(fit_pp_2,newdata = test_data)
test_data$pp_3_pred <- predict.lm(fit_pp_3,newdata = test_data)
test_data$pp_4_pred <- predict.lm(fit_pp_4,newdata = test_data)
test_data$pp_5_pred <- predict.lm(fit_pp_5,newdata = test_data)

# calculating residuals platform


test_data$pz_1_res <- test_data$pz_1 - test_data$pz_1_pred
test_data$pz_2_res <- test_data$pz_2 - test_data$pz_2_pred
test_data$pz_3_res <- test_data$pz_3 - test_data$pz_3_pred
test_data$pz_4_res <- test_data$pz_4 - test_data$pz_4_pred
test_data$pz_5_res <- test_data$pz_5 - test_data$pz_5_pred

test_data$pp_1_res <- test_data$pp_1 - test_data$pp_1_pred
test_data$pp_2_res <- test_data$pp_2 - test_data$pp_2_pred
test_data$pp_3_res <- test_data$pp_3 - test_data$pp_3_pred
test_data$pp_4_res <- test_data$pp_4 - test_data$pp_4_pred
test_data$pp_5_res <- test_data$pp_5 - test_data$pp_5_pred

# WHEELS SINGLE

fit_az_1l_1 <- lm(formula = az_1l_1 ~ az_2l_1 + az_3l_1 + az_4l_1 +
                      az_1r_1 + az_2r_1 + az_3r_1 + az_4r_1 + Payload + Speed, data = train_data)
fit_az_2l_1 <- lm(formula = az_2l_1 ~ az_1l_1 + az_3l_1 + az_4l_1 +
                      az_1r_1 + az_2r_1 + az_3r_1 + az_4r_1 + Payload + Speed, data = train_data)
fit_az_3l_1 <- lm(formula = az_3l_1 ~ az_1l_1 +  az_2l_1 + az_4l_1 +
                      az_1r_1 + az_2r_1 + az_3r_1 + az_4r_1 + Payload + Speed, data = train_data)
fit_az_4l_1 <- lm(formula = az_4l_1 ~ az_1l_1 + az_2l_1 + az_3l_1 +
                      az_1r_1 + az_2r_1 + az_3r_1 + az_4r_1 + Payload + Speed, data = train_data)
fit_az_1r_1 <- lm(formula = az_1r_1 ~ az_1l_1 + az_2l_1 + az_3l_1 + az_4l_1 +
                      az_2r_1 + az_3r_1 + az_4r_1 + Payload + Speed, data = train_data)
fit_az_2r_1 <- lm(formula = az_2r_1 ~ az_1l_1 + az_2l_1 + az_3l_1 + az_4l_1 +
                      az_1r_1 + az_3r_1 + az_4r_1 + Payload + Speed, data = train_data)
fit_az_3r_1 <- lm(formula = az_3r_1 ~ az_1l_1 + az_2l_1 + az_3l_1 + az_4l_1 +
                      az_1r_1 + az_2r_1 + az_4r_1 + Payload + Speed, data = train_data)
fit_az_4r_1 <- lm(formula = az_4r_1 ~ az_1l_1 + az_2l_1 + az_3l_1 + az_4l_1 +
                      az_1r_1 + az_2r_1 + az_3r_1 + Payload + Speed, data = train_data)


fit_az_1l_2 <- lm(formula = az_1l_2 ~ az_2l_2 + az_3l_2 + az_4l_2 +
                      az_1r_2 + az_2r_2 + az_3r_2 + az_4r_2 + Payload + Speed, data = train_data)
fit_az_2l_2 <- lm(formula = az_2l_2 ~ az_1l_2 + az_3l_2 + az_4l_2 +
                      az_1r_2 + az_2r_2 + az_3r_2 + az_4r_2 + Payload + Speed, data = train_data)
fit_az_3l_2 <- lm(formula = az_3l_2 ~ az_1l_2 +  az_2l_2 + az_4l_2 +
                      az_1r_2 + az_2r_2 + az_3r_2 + az_4r_2 + Payload + Speed, data = train_data)
fit_az_4l_2 <- lm(formula = az_4l_2 ~ az_1l_2 + az_2l_2 + az_3l_2 +
                      az_1r_2 + az_2r_2 + az_3r_2 + az_4r_2 + Payload + Speed, data = train_data)
fit_az_1r_2 <- lm(formula = az_1r_2 ~ az_1l_2 + az_2l_2 + az_3l_2 + az_4l_2 +
                      az_2r_2 + az_3r_2 + az_4r_2 + Payload + Speed, data = train_data)
fit_az_2r_2 <- lm(formula = az_2r_2 ~ az_1l_2 + az_2l_2 + az_3l_2 + az_4l_2 +
                      az_1r_2 + az_3r_2 + az_4r_2 + Payload + Speed, data = train_data)
fit_az_3r_2 <- lm(formula = az_3r_2 ~ az_1l_2 + az_2l_2 + az_3l_2 + az_4l_2 +
                      az_1r_2 + az_2r_2 + az_4r_2 + Payload + Speed, data = train_data)
fit_az_4r_2 <- lm(formula = az_4r_2 ~ az_1l_2 + az_2l_2 + az_3l_2 + az_4l_2 +
                      az_1r_2 + az_2r_2 + az_3r_2 + Payload + Speed, data = train_data)


fit_az_1l_3 <- lm(formula = az_1l_3 ~ az_2l_3 + az_3l_3 + az_4l_3 +
                      az_1r_3 + az_2r_3 + az_3r_3 + az_4r_3 + Payload + Speed, data = train_data)
fit_az_2l_3 <- lm(formula = az_2l_3 ~ az_1l_3 + az_3l_3 + az_4l_3 +
                      az_1r_3 + az_2r_3 + az_3r_3 + az_4r_3 + Payload + Speed, data = train_data)
fit_az_3l_3 <- lm(formula = az_3l_3 ~ az_1l_3 +  az_2l_3 + az_4l_3 +
                      az_1r_3 + az_2r_3 + az_3r_3 + az_4r_3 + Payload + Speed, data = train_data)
fit_az_4l_3 <- lm(formula = az_4l_3 ~ az_1l_3 + az_2l_3 + az_3l_3 +
                      az_1r_3 + az_2r_3 + az_3r_3 + az_4r_3 + Payload + Speed, data = train_data)
fit_az_1r_3 <- lm(formula = az_1r_3 ~ az_1l_3 + az_2l_3 + az_3l_3 + az_4l_3 +
                      az_2r_3 + az_3r_3 + az_4r_3 + Payload + Speed, data = train_data)
fit_az_2r_3 <- lm(formula = az_2r_3 ~ az_1l_3 + az_2l_3 + az_3l_3 + az_4l_3 +
                      az_1r_3 + az_3r_3 + az_4r_3 + Payload + Speed, data = train_data)
fit_az_3r_3 <- lm(formula = az_3r_3 ~ az_1l_3 + az_2l_3 + az_3l_3 + az_4l_3 +
                      az_1r_3 + az_2r_3 + az_4r_3 + Payload + Speed, data = train_data)
fit_az_4r_3 <- lm(formula = az_4r_3 ~ az_1l_3 + az_2l_3 + az_3l_3 + az_4l_3 +
                      az_1r_3 + az_2r_3 + az_3r_3 + Payload + Speed, data = train_data)



fit_az_1l_4 <- lm(formula = az_1l_4 ~ az_2l_4 + az_3l_4 + az_4l_4 +
                      az_1r_4 + az_2r_4 + az_3r_4 + az_4r_4 + Payload + Speed, data = train_data)
fit_az_2l_4 <- lm(formula = az_2l_4 ~ az_1l_4 + az_3l_4 + az_4l_4 +
                      az_1r_4 + az_2r_4 + az_3r_4 + az_4r_4 + Payload + Speed, data = train_data)
fit_az_3l_4 <- lm(formula = az_3l_4 ~ az_1l_4 +  az_2l_4 + az_4l_4 +
                      az_1r_4 + az_2r_4 + az_3r_4 + az_4r_4 + Payload + Speed, data = train_data)
fit_az_4l_4 <- lm(formula = az_4l_4 ~ az_1l_4 + az_2l_4 + az_3l_4 +
                      az_1r_4 + az_2r_4 + az_3r_4 + az_4r_4 + Payload + Speed, data = train_data)
fit_az_1r_4 <- lm(formula = az_1r_4 ~ az_1l_4 + az_2l_4 + az_3l_4 + az_4l_4 +
                      az_2r_4 + az_3r_4 + az_4r_4 + Payload + Speed, data = train_data)
fit_az_2r_4 <- lm(formula = az_2r_4 ~ az_1l_4 + az_2l_4 + az_3l_4 + az_4l_4 +
                      az_1r_4 + az_3r_4 + az_4r_4 + Payload + Speed, data = train_data)
fit_az_3r_4 <- lm(formula = az_3r_4 ~ az_1l_4 + az_2l_4 + az_3l_4 + az_4l_4 +
                      az_1r_4 + az_2r_4 + az_4r_4 + Payload + Speed, data = train_data)
fit_az_4r_4 <- lm(formula = az_4r_4 ~ az_1l_4 + az_2l_4 + az_3l_4 + az_4l_4 +
                      az_1r_4 + az_2r_4 + az_3r_4 + Payload + Speed, data = train_data)


fit_az_1l_5  <- lm(formula = az_1l_5  ~ az_2l_5  + az_3l_5  + az_4l_5  +
                      az_1r_5  + az_2r_5  + az_3r_5  + az_4r_5  + Payload + Speed, data = train_data)
fit_az_2l_5  <- lm(formula = az_2l_5  ~ az_1l_5  + az_3l_5  + az_4l_5  +
                      az_1r_5  + az_2r_5  + az_3r_5  + az_4r_5  + Payload + Speed, data = train_data)
fit_az_3l_5  <- lm(formula = az_3l_5  ~ az_1l_5  +  az_2l_5  + az_4l_5  +
                      az_1r_5  + az_2r_5  + az_3r_5  + az_4r_5  + Payload + Speed, data = train_data)
fit_az_4l_5  <- lm(formula = az_4l_5  ~ az_1l_5  + az_2l_5  + az_3l_5  +
                      az_1r_5  + az_2r_5  + az_3r_5  + az_4r_5  + Payload + Speed, data = train_data)
fit_az_1r_5  <- lm(formula = az_1r_5  ~ az_1l_5  + az_2l_5  + az_3l_5  + az_4l_5  +
                      az_2r_5  + az_3r_5  + az_4r_5  + Payload + Speed, data = train_data)
fit_az_2r_5  <- lm(formula = az_2r_5  ~ az_1l_5  + az_2l_5  + az_3l_5  + az_4l_5  +
                      az_1r_5  + az_3r_5  + az_4r_5  + Payload + Speed, data = train_data)
fit_az_3r_5  <- lm(formula = az_3r_5  ~ az_1l_5  + az_2l_5  + az_3l_5  + az_4l_5  +
                      az_1r_5  + az_2r_5  + az_4r_5  + Payload + Speed, data = train_data)
fit_az_4r_5  <- lm(formula = az_4r_5  ~ az_1l_5  + az_2l_5  + az_3l_5  + az_4l_5  +
                      az_1r_5  + az_2r_5  + az_3r_5  + Payload + Speed, data = train_data)

# Predict on wheels

test_data$az_1r_1_pred <- predict.lm(fit_az_1r_1, newdata = test_data)
test_data$az_2r_1_pred <- predict.lm(fit_az_2r_1, newdata = test_data)
test_data$az_3r_1_pred <- predict.lm(fit_az_3r_1, newdata = test_data)
test_data$az_4r_1_pred <- predict.lm(fit_az_4r_1, newdata = test_data)

test_data$az_1l_1_pred <- predict.lm(fit_az_1l_1, newdata = test_data)
test_data$az_2l_1_pred <- predict.lm(fit_az_2l_1, newdata = test_data)
test_data$az_3l_1_pred <- predict.lm(fit_az_3l_1, newdata = test_data)
test_data$az_4l_1_pred <- predict.lm(fit_az_4l_1, newdata = test_data)

test_data$az_1r_2_pred <- predict.lm(fit_az_1r_2, newdata = test_data)
test_data$az_2r_2_pred <- predict.lm(fit_az_2r_2, newdata = test_data)
test_data$az_3r_2_pred <- predict.lm(fit_az_3r_2, newdata = test_data)
test_data$az_4r_2_pred <- predict.lm(fit_az_4r_2, newdata = test_data)

test_data$az_1l_2_pred <- predict.lm(fit_az_1l_2, newdata = test_data)
test_data$az_2l_2_pred <- predict.lm(fit_az_2l_2, newdata = test_data)
test_data$az_3l_2_pred <- predict.lm(fit_az_3l_2, newdata = test_data)
test_data$az_4l_2_pred <- predict.lm(fit_az_4l_2, newdata = test_data)

test_data$az_1r_3_pred <- predict.lm(fit_az_1r_3, newdata = test_data)
test_data$az_2r_3_pred <- predict.lm(fit_az_2r_3, newdata = test_data)
test_data$az_3r_3_pred <- predict.lm(fit_az_3r_3, newdata = test_data)
test_data$az_4r_3_pred <- predict.lm(fit_az_4r_3, newdata = test_data)

test_data$az_1l_3_pred <- predict.lm(fit_az_1l_3, newdata = test_data)
test_data$az_2l_3_pred <- predict.lm(fit_az_2l_3, newdata = test_data)
test_data$az_3l_3_pred <- predict.lm(fit_az_3l_3, newdata = test_data)
test_data$az_4l_3_pred <- predict.lm(fit_az_4l_3, newdata = test_data)

test_data$az_1r_4_pred <- predict.lm(fit_az_1r_4, newdata = test_data)
test_data$az_2r_4_pred <- predict.lm(fit_az_2r_4, newdata = test_data)
test_data$az_3r_4_pred <- predict.lm(fit_az_3r_4, newdata = test_data)
test_data$az_4r_4_pred <- predict.lm(fit_az_4r_4, newdata = test_data)

test_data$az_1l_4_pred <- predict.lm(fit_az_1l_4, newdata = test_data)
test_data$az_2l_4_pred <- predict.lm(fit_az_2l_4, newdata = test_data)
test_data$az_3l_4_pred <- predict.lm(fit_az_3l_4, newdata = test_data)
test_data$az_4l_4_pred <- predict.lm(fit_az_4l_4, newdata = test_data)

test_data$az_1r_5_pred <- predict.lm(fit_az_1r_5, newdata = test_data)
test_data$az_2r_5_pred <- predict.lm(fit_az_2r_5, newdata = test_data)
test_data$az_3r_5_pred <- predict.lm(fit_az_3r_5, newdata = test_data)
test_data$az_4r_5_pred <- predict.lm(fit_az_4r_5, newdata = test_data)

test_data$az_1l_5_pred <- predict.lm(fit_az_1l_5, newdata = test_data)
test_data$az_2l_5_pred <- predict.lm(fit_az_2l_5, newdata = test_data)
test_data$az_3l_5_pred <- predict.lm(fit_az_3l_5, newdata = test_data)
test_data$az_4l_5_pred <- predict.lm(fit_az_4l_5, newdata = test_data)


# Wheels residuals`
test_data$az_1l_1_res <- test_data$az_1l_1 - test_data$az_1l_1_pred
test_data$az_2l_1_res <- test_data$az_2l_1 - test_data$az_2l_1_pred
test_data$az_3l_1_res <- test_data$az_3l_1 - test_data$az_3l_1_pred
test_data$az_4l_1_res <- test_data$az_4l_1 - test_data$az_4l_1_pred

test_data$az_1r_1_res <- test_data$az_1r_1 - test_data$az_1r_1_pred
test_data$az_2r_1_res <- test_data$az_2r_1 - test_data$az_2r_1_pred
test_data$az_3r_1_res <- test_data$az_3r_1 - test_data$az_3r_1_pred
test_data$az_4r_1_res <- test_data$az_4r_1 - test_data$az_4r_1_pred

test_data$az_1l_2_res <- test_data$az_1l_2 - test_data$az_1l_2_pred
test_data$az_2l_2_res <- test_data$az_2l_2 - test_data$az_2l_2_pred
test_data$az_3l_2_res <- test_data$az_3l_2 - test_data$az_3l_2_pred
test_data$az_4l_2_res <- test_data$az_4l_2 - test_data$az_4l_2_pred

test_data$az_1r_2_res <- test_data$az_1r_2 - test_data$az_1r_2_pred
test_data$az_2r_2_res <- test_data$az_2r_2 - test_data$az_2r_2_pred
test_data$az_3r_2_res <- test_data$az_3r_2 - test_data$az_3r_2_pred
test_data$az_4r_2_res <- test_data$az_4r_2 - test_data$az_4r_2_pred

test_data$az_1l_3_res <- test_data$az_1l_3 - test_data$az_1l_3_pred
test_data$az_2l_3_res <- test_data$az_2l_3 - test_data$az_2l_3_pred
test_data$az_3l_3_res <- test_data$az_3l_3 - test_data$az_3l_3_pred
test_data$az_4l_3_res <- test_data$az_4l_3 - test_data$az_4l_3_pred

test_data$az_1r_3_res <- test_data$az_1r_3 - test_data$az_1r_3_pred
test_data$az_2r_3_res <- test_data$az_2r_3 - test_data$az_2r_3_pred
test_data$az_3r_3_res <- test_data$az_3r_3 - test_data$az_3r_3_pred
test_data$az_4r_3_res <- test_data$az_4r_3 - test_data$az_4r_3_pred

test_data$az_1l_4_res <- test_data$az_1l_4 - test_data$az_1l_4_pred
test_data$az_2l_4_res <- test_data$az_2l_4 - test_data$az_2l_4_pred
test_data$az_3l_4_res <- test_data$az_3l_4 - test_data$az_3l_4_pred
test_data$az_4l_4_res <- test_data$az_4l_4 - test_data$az_4l_4_pred

test_data$az_1r_4_res <- test_data$az_1r_4 - test_data$az_1r_4_pred
test_data$az_2r_4_res <- test_data$az_2r_4 - test_data$az_2r_4_pred
test_data$az_3r_4_res <- test_data$az_3r_4 - test_data$az_3r_4_pred
test_data$az_4r_4_res <- test_data$az_4r_4 - test_data$az_4r_4_pred

test_data$az_1l_5_res <- test_data$az_1l_5 - test_data$az_1l_5_pred
test_data$az_2l_5_res <- test_data$az_2l_5 - test_data$az_2l_5_pred
test_data$az_3l_5_res <- test_data$az_3l_5 - test_data$az_3l_5_pred
test_data$az_4l_5_res <- test_data$az_4l_5 - test_data$az_4l_5_pred

test_data$az_1r_5_res <- test_data$az_1r_5 - test_data$az_1r_5_pred
test_data$az_2r_5_res <- test_data$az_2r_5 - test_data$az_2r_5_pred
test_data$az_3r_5_res <- test_data$az_3r_5 - test_data$az_3r_5_pred
test_data$az_4r_5_res <- test_data$az_4r_5 - test_data$az_4r_5_pred
```


```{r Fits on training sets validation}

# b1z
train_data$b1z_1_pred <- predict.lm(fit_b1z_1,newdata = train_data)
train_data$b1z_2_pred <- predict.lm(fit_b1z_2,newdata = train_data)
train_data$b1z_3_pred <- predict.lm(fit_b1z_3,newdata = train_data)
train_data$b1z_4_pred <- predict.lm(fit_b1z_4,newdata = train_data)
train_data$b1z_5_pred <- predict.lm(fit_b1z_5,newdata = train_data)


# b1r
train_data$b1r_1_pred <- predict.lm(fit_b1r_1,newdata = train_data)
train_data$b1r_2_pred <- predict.lm(fit_b1r_2,newdata = train_data)
train_data$b1r_3_pred <- predict.lm(fit_b1r_3,newdata = train_data)
train_data$b1r_4_pred <- predict.lm(fit_b1r_4,newdata = train_data)
train_data$b1r_5_pred <- predict.lm(fit_b1r_5,newdata = train_data)

# b1p
train_data$b1p_1_pred <- predict.lm(fit_b1p_1,newdata = train_data)
train_data$b1p_2_pred <- predict.lm(fit_b1p_2,newdata = train_data)
train_data$b1p_3_pred <- predict.lm(fit_b1p_3,newdata = train_data)
train_data$b1p_4_pred <- predict.lm(fit_b1p_4,newdata = train_data)
train_data$b1p_5_pred <- predict.lm(fit_b1p_5,newdata = train_data)

#b2z
train_data$b2z_1_pred <- predict.lm(fit_b2z_1,newdata = train_data)
train_data$b2z_2_pred <- predict.lm(fit_b2z_2,newdata = train_data)
train_data$b2z_3_pred <- predict.lm(fit_b2z_3,newdata = train_data)
train_data$b2z_4_pred <- predict.lm(fit_b2z_4,newdata = train_data)
train_data$b2z_5_pred <- predict.lm(fit_b2z_5,newdata = train_data)

# b2r
train_data$b2r_1_pred <- predict.lm(fit_b2r_1,newdata = train_data)
train_data$b2r_2_pred <- predict.lm(fit_b2r_2,newdata = train_data)
train_data$b2r_3_pred <- predict.lm(fit_b2r_3,newdata = train_data)
train_data$b2r_4_pred <- predict.lm(fit_b2r_4,newdata = train_data)
train_data$b2r_5_pred <- predict.lm(fit_b2r_5,newdata = train_data)

# b2p
train_data$b2p_1_pred <- predict.lm(fit_b2p_1,newdata = train_data)
train_data$b2p_2_pred <- predict.lm(fit_b2p_2,newdata = train_data)
train_data$b2p_3_pred <- predict.lm(fit_b2p_3,newdata = train_data)
train_data$b2p_4_pred <- predict.lm(fit_b2p_4,newdata = train_data)
train_data$b2p_5_pred <- predict.lm(fit_b2p_5,newdata = train_data)

# calculating residuals

train_data$b1z_1_res <- train_data$b1z_1 - train_data$b1z_1_pred
train_data$b1z_2_res <- train_data$b1z_2 - train_data$b1z_2_pred
train_data$b1z_3_res <- train_data$b1z_3 - train_data$b1z_3_pred
train_data$b1z_4_res <- train_data$b1z_4 - train_data$b1z_4_pred
train_data$b1z_5_res <- train_data$b1z_5 - train_data$b1z_5_pred

train_data$b1r_1_res <- train_data$b1r_1 - train_data$b1r_1_pred
train_data$b1r_2_res <- train_data$b1r_2 - train_data$b1r_2_pred
train_data$b1r_3_res <- train_data$b1r_3 - train_data$b1r_3_pred
train_data$b1r_4_res <- train_data$b1r_4 - train_data$b1r_4_pred
train_data$b1r_5_res <- train_data$b1r_5 - train_data$b1r_5_pred

train_data$b1p_1_res <- train_data$b1p_1 - train_data$b1p_1_pred
train_data$b1p_2_res <- train_data$b1p_2 - train_data$b1p_2_pred
train_data$b1p_3_res <- train_data$b1p_3 - train_data$b1p_3_pred
train_data$b1p_4_res <- train_data$b1p_4 - train_data$b1p_4_pred
train_data$b1p_5_res <- train_data$b1p_5 - train_data$b1p_5_pred

#b2
train_data$b2z_1_res <- train_data$b2z_1 - train_data$b2z_1_pred
train_data$b2z_2_res <- train_data$b2z_2 - train_data$b2z_2_pred
train_data$b2z_3_res <- train_data$b2z_3 - train_data$b2z_3_pred
train_data$b2z_4_res <- train_data$b2z_4 - train_data$b2z_4_pred
train_data$b2z_5_res <- train_data$b2z_5 - train_data$b2z_5_pred

train_data$b2r_1_res <- train_data$b2r_1 - train_data$b2r_1_pred
train_data$b2r_2_res <- train_data$b2r_2 - train_data$b2r_2_pred
train_data$b2r_3_res <- train_data$b2r_3 - train_data$b2r_3_pred
train_data$b2r_4_res <- train_data$b2r_4 - train_data$b2r_4_pred
train_data$b2r_5_res <- train_data$b2r_5 - train_data$b2r_5_pred

train_data$b2p_1_res <- train_data$b2p_1 - train_data$b2p_1_pred
train_data$b2p_2_res <- train_data$b2p_2 - train_data$b2p_2_pred
train_data$b2p_3_res <- train_data$b2p_3 - train_data$b2p_3_pred
train_data$b2p_4_res <- train_data$b2p_4 - train_data$b2p_4_pred
train_data$b2p_5_res <- train_data$b2p_5 - train_data$b2p_5_pred

# Platform
# PZ
# predictions platform
train_data$pz_1_pred <- predict.lm(fit_pz_1,newdata = train_data)
train_data$pz_2_pred <- predict.lm(fit_pz_2,newdata = train_data)
train_data$pz_3_pred <- predict.lm(fit_pz_3,newdata = train_data)
train_data$pz_4_pred <- predict.lm(fit_pz_4,newdata = train_data)
train_data$pz_5_pred <- predict.lm(fit_pz_5,newdata = train_data)

train_data$pp_1_pred <- predict.lm(fit_pp_1,newdata = train_data)
train_data$pp_2_pred <- predict.lm(fit_pp_2,newdata = train_data)
train_data$pp_3_pred <- predict.lm(fit_pp_3,newdata = train_data)
train_data$pp_4_pred <- predict.lm(fit_pp_4,newdata = train_data)
train_data$pp_5_pred <- predict.lm(fit_pp_5,newdata = train_data)

# calculating residuals platform
train_data$pz_1_res <- train_data$pz_1 - train_data$pz_1_pred
train_data$pz_2_res <- train_data$pz_2 - train_data$pz_2_pred
train_data$pz_3_res <- train_data$pz_3 - train_data$pz_3_pred
train_data$pz_4_res <- train_data$pz_4 - train_data$pz_4_pred
train_data$pz_5_res <- train_data$pz_5 - train_data$pz_5_pred

train_data$pp_1_res <- train_data$pp_1 - train_data$pp_1_pred
train_data$pp_2_res <- train_data$pp_2 - train_data$pp_2_pred
train_data$pp_3_res <- train_data$pp_3 - train_data$pp_3_pred
train_data$pp_4_res <- train_data$pp_4 - train_data$pp_4_pred
train_data$pp_5_res <- train_data$pp_5 - train_data$pp_5_pred

# WHEELS SINGLE
# Predict on wheels
train_data$az_1r_1_pred <- predict.lm(fit_az_1r_1, newdata = train_data)
train_data$az_2r_1_pred <- predict.lm(fit_az_2r_1, newdata = train_data)
train_data$az_3r_1_pred <- predict.lm(fit_az_3r_1, newdata = train_data)
train_data$az_4r_1_pred <- predict.lm(fit_az_4r_1, newdata = train_data)

train_data$az_1l_1_pred <- predict.lm(fit_az_1l_1, newdata = train_data)
train_data$az_2l_1_pred <- predict.lm(fit_az_2l_1, newdata = train_data)
train_data$az_3l_1_pred <- predict.lm(fit_az_3l_1, newdata = train_data)
train_data$az_4l_1_pred <- predict.lm(fit_az_4l_1, newdata = train_data)

train_data$az_1r_2_pred <- predict.lm(fit_az_1r_2, newdata = train_data)
train_data$az_2r_2_pred <- predict.lm(fit_az_2r_2, newdata = train_data)
train_data$az_3r_2_pred <- predict.lm(fit_az_3r_2, newdata = train_data)
train_data$az_4r_2_pred <- predict.lm(fit_az_4r_2, newdata = train_data)

train_data$az_1l_2_pred <- predict.lm(fit_az_1l_2, newdata = train_data)
train_data$az_2l_2_pred <- predict.lm(fit_az_2l_2, newdata = train_data)
train_data$az_3l_2_pred <- predict.lm(fit_az_3l_2, newdata = train_data)
train_data$az_4l_2_pred <- predict.lm(fit_az_4l_2, newdata = train_data)

train_data$az_1r_3_pred <- predict.lm(fit_az_1r_3, newdata = train_data)
train_data$az_2r_3_pred <- predict.lm(fit_az_2r_3, newdata = train_data)
train_data$az_3r_3_pred <- predict.lm(fit_az_3r_3, newdata = train_data)
train_data$az_4r_3_pred <- predict.lm(fit_az_4r_3, newdata = train_data)

train_data$az_1l_3_pred <- predict.lm(fit_az_1l_3, newdata = train_data)
train_data$az_2l_3_pred <- predict.lm(fit_az_2l_3, newdata = train_data)
train_data$az_3l_3_pred <- predict.lm(fit_az_3l_3, newdata = train_data)
train_data$az_4l_3_pred <- predict.lm(fit_az_4l_3, newdata = train_data)

train_data$az_1r_4_pred <- predict.lm(fit_az_1r_4, newdata = train_data)
train_data$az_2r_4_pred <- predict.lm(fit_az_2r_4, newdata = train_data)
train_data$az_3r_4_pred <- predict.lm(fit_az_3r_4, newdata = train_data)
train_data$az_4r_4_pred <- predict.lm(fit_az_4r_4, newdata = train_data)

train_data$az_1l_4_pred <- predict.lm(fit_az_1l_4, newdata = train_data)
train_data$az_2l_4_pred <- predict.lm(fit_az_2l_4, newdata = train_data)
train_data$az_3l_4_pred <- predict.lm(fit_az_3l_4, newdata = train_data)
train_data$az_4l_4_pred <- predict.lm(fit_az_4l_4, newdata = train_data)

train_data$az_1r_5_pred <- predict.lm(fit_az_1r_5, newdata = train_data)
train_data$az_2r_5_pred <- predict.lm(fit_az_2r_5, newdata = train_data)
train_data$az_3r_5_pred <- predict.lm(fit_az_3r_5, newdata = train_data)
train_data$az_4r_5_pred <- predict.lm(fit_az_4r_5, newdata = train_data)

train_data$az_1l_5_pred <- predict.lm(fit_az_1l_5, newdata = train_data)
train_data$az_2l_5_pred <- predict.lm(fit_az_2l_5, newdata = train_data)
train_data$az_3l_5_pred <- predict.lm(fit_az_3l_5, newdata = train_data)
train_data$az_4l_5_pred <- predict.lm(fit_az_4l_5, newdata = train_data)


# Wheels residuals`
train_data$az_1l_1_res <- train_data$az_1l_1 - train_data$az_1l_1_pred
train_data$az_2l_1_res <- train_data$az_2l_1 - train_data$az_2l_1_pred
train_data$az_3l_1_res <- train_data$az_3l_1 - train_data$az_3l_1_pred
train_data$az_4l_1_res <- train_data$az_4l_1 - train_data$az_4l_1_pred

train_data$az_1r_1_res <- train_data$az_1r_1 - train_data$az_1r_1_pred
train_data$az_2r_1_res <- train_data$az_2r_1 - train_data$az_2r_1_pred
train_data$az_3r_1_res <- train_data$az_3r_1 - train_data$az_3r_1_pred
train_data$az_4r_1_res <- train_data$az_4r_1 - train_data$az_4r_1_pred

train_data$az_1l_2_res <- train_data$az_1l_2 - train_data$az_1l_2_pred
train_data$az_2l_2_res <- train_data$az_2l_2 - train_data$az_2l_2_pred
train_data$az_3l_2_res <- train_data$az_3l_2 - train_data$az_3l_2_pred
train_data$az_4l_2_res <- train_data$az_4l_2 - train_data$az_4l_2_pred

train_data$az_1r_2_res <- train_data$az_1r_2 - train_data$az_1r_2_pred
train_data$az_2r_2_res <- train_data$az_2r_2 - train_data$az_2r_2_pred
train_data$az_3r_2_res <- train_data$az_3r_2 - train_data$az_3r_2_pred
train_data$az_4r_2_res <- train_data$az_4r_2 - train_data$az_4r_2_pred

train_data$az_1l_3_res <- train_data$az_1l_3 - train_data$az_1l_3_pred
train_data$az_2l_3_res <- train_data$az_2l_3 - train_data$az_2l_3_pred
train_data$az_3l_3_res <- train_data$az_3l_3 - train_data$az_3l_3_pred
train_data$az_4l_3_res <- train_data$az_4l_3 - train_data$az_4l_3_pred

train_data$az_1r_3_res <- train_data$az_1r_3 - train_data$az_1r_3_pred
train_data$az_2r_3_res <- train_data$az_2r_3 - train_data$az_2r_3_pred
train_data$az_3r_3_res <- train_data$az_3r_3 - train_data$az_3r_3_pred
train_data$az_4r_3_res <- train_data$az_4r_3 - train_data$az_4r_3_pred

train_data$az_1l_4_res <- train_data$az_1l_4 - train_data$az_1l_4_pred
train_data$az_2l_4_res <- train_data$az_2l_4 - train_data$az_2l_4_pred
train_data$az_3l_4_res <- train_data$az_3l_4 - train_data$az_3l_4_pred
train_data$az_4l_4_res <- train_data$az_4l_4 - train_data$az_4l_4_pred

train_data$az_1r_4_res <- train_data$az_1r_4 - train_data$az_1r_4_pred
train_data$az_2r_4_res <- train_data$az_2r_4 - train_data$az_2r_4_pred
train_data$az_3r_4_res <- train_data$az_3r_4 - train_data$az_3r_4_pred
train_data$az_4r_4_res <- train_data$az_4r_4 - train_data$az_4r_4_pred

train_data$az_1l_5_res <- train_data$az_1l_5 - train_data$az_1l_5_pred
train_data$az_2l_5_res <- train_data$az_2l_5 - train_data$az_2l_5_pred
train_data$az_3l_5_res <- train_data$az_3l_5 - train_data$az_3l_5_pred
train_data$az_4l_5_res <- train_data$az_4l_5 - train_data$az_4l_5_pred

train_data$az_1r_5_res <- train_data$az_1r_5 - train_data$az_1r_5_pred
train_data$az_2r_5_res <- train_data$az_2r_5 - train_data$az_2r_5_pred
train_data$az_3r_5_res <- train_data$az_3r_5 - train_data$az_3r_5_pred
train_data$az_4r_5_res <- train_data$az_4r_5 - train_data$az_4r_5_pred

```



## Summarise all data

```{r Summary data}
test_data_summ <- test_data %>% select(ExperimentID, contains("_res")) %>% group_by(ExperimentID) %>%
    summarise_each(funs(mean, median, q25 = quantile(.,c(.25)), q75 = quantile(.,c(.75)), sd, IQR)) %>%
    ungroup()

train_data_summ <- train_data %>% select(ExperimentID, contains("_res")) %>% group_by(ExperimentID) %>%
    summarise_each(funs(mean, median, q25 = quantile(.,c(.25)), q75 = quantile(.,c(.75)), sd, IQR)) %>%
    ungroup()

```

## residuals plots  

```{r residual plots}

train_data %>%
  ggplot(.)+
  geom_histogram(aes(x=resid(fit_b1z_2)),alpha=0.5, fill="blue", binwidth = 0.01)+
  geom_histogram(aes(x=resid(fit_b1z_3)),alpha=0.5, fill="green", binwidth = 0.01)+
  geom_histogram(aes(x=resid(fit_b1z_4)),alpha=0.5, fill="red", binwidth = 0.01)+
  geom_histogram(aes(x=resid(fit_b1z_5)),alpha=0.5, fill="orange", binwidth = 0.01)+
  coord_cartesian(xlim=c(-1,1))

test_data %>%
  ggplot(.)+
  geom_histogram(aes(x=b1z_2_res),alpha=0.5, fill = "blue", binwidth = 0.01)+
  geom_histogram(aes(x=b1z_3_res),alpha=0.5, fill = "green", binwidth = 0.01)+
  geom_histogram(aes(x=b1z_4_res),alpha=0.5, fill = "red", binwidth = 0.01)+
  geom_histogram(aes(x=b1z_5_res),alpha=0.5, fill = "orange", binwidth = 0.01)+
  facet_wrap(~Speed)+
  coord_cartesian(xlim=c(-1,1))

test_data %>%
  ggplot(.)+
  geom_histogram(aes(x=b1r_2_res),alpha=0.5, fill = "blue", binwidth = 0.01)+
  geom_histogram(aes(x=b1r_3_res),alpha=0.5, fill = "green", binwidth = 0.01)+
  geom_histogram(aes(x=b1r_4_res),alpha=0.5, fill = "red", binwidth = 0.01)+
  geom_histogram(aes(x=b1r_5_res),alpha=0.5, fill = "orange", binwidth = 0.01)+
  facet_wrap(~Speed)+
  coord_cartesian(xlim=c(-1,1))
```

## pred vs. actual plots

```{r plots - predicted vs. actual}
test_data %>% filter(ExperimentID <10) %>%
  ggplot(.,aes(x=b1z_2,y=b1z_2_pred,color=as.factor(ExperimentID)))+
  geom_point()+
  geom_abline(aes(slope=1,intercept=0.0))

test_data %>% filter(ExperimentID <20) %>%
  ggplot(.,aes(x=b1z_3,y=b1z_3_pred,color=as.factor(ExperimentID)))+
  geom_point()+
  geom_abline(aes(slope=1,intercept=0.0))

test_data %>% filter(ExperimentID <20) %>%
  ggplot(.,aes(x=b1z_4,y=b1z_4_pred,color=as.factor(ExperimentID)))+
  geom_point()+
  geom_abline(aes(slope=1,intercept=0.0))

test_data %>% filter(ExperimentID <20) %>%
  ggplot(.,aes(x=b1z_5,y=b1z_5_pred,color=as.factor(ExperimentID)))+
  geom_point()+
  geom_abline(aes(slope=1,intercept=0.0))

test_data %>% filter(ExperimentID <20) %>%
  ggplot(.,aes(x=b2z_5,y=b2z_5_pred,color=as.factor(ExperimentID)))+
  geom_point()+
  geom_abline(aes(slope=1,intercept=0.0))

test_data %>% filter(ExperimentID <10) %>%
  ggplot(.,aes(x=b1r_2,y=b1r_2_pred,color=as.factor(ExperimentID)))+
  geom_point()+
  geom_abline(aes(slope=1,intercept=0.0))

test_data %>% filter(ExperimentID <20) %>%
  ggplot(.,aes(x=b1r_3,y=b1r_3_pred,color=as.factor(ExperimentID)))+
  geom_point()+
  geom_abline(aes(slope=1,intercept=0.0))

test_data %>% filter(ExperimentID <20) %>%
  ggplot(.,aes(x=b1r_4,y=b1r_4_pred,color=as.factor(ExperimentID)))+
  geom_point()+
  geom_abline(aes(slope=1,intercept=0.0))

test_data %>% filter(ExperimentID <20) %>%
  ggplot(.,aes(x=b1r_5,y=b1r_5_pred,color=as.factor(ExperimentID)))+
  geom_point()+
  geom_abline(aes(slope=1,intercept=0.0))

test_data %>% filter(ExperimentID <20) %>%
  ggplot(.,aes(x=b2r_5,y=b2r_5_pred,color=as.factor(ExperimentID)))+
  geom_point()+
  geom_abline(aes(slope=1,intercept=0.0))

```
  
## BACKUP {.tabset}    

also known as previus/old stuff  

### Stuff  


### check plots

```{r plots1, fig.height=12, fig.width=12}
#z motion - front bogie
train_data %>% 
  ggplot(.,aes(x=azp_1_2+azp_2_2, y=az_1r_2+az_1l_2+az_2l_2+az_2r_2, color=as.factor(Speed)))+geom_point()+
  labs(title = " train set - front bogie - z motion - all points")+
  geom_abline(aes(slope =1, intercept=0.0))

test_data %>% 
  ggplot(.,aes(x=azp_1_2+azp_2_2, y=az_1r_2+az_1l_2+az_2l_2+az_2r_2, color=as.factor(Speed)))+geom_point()+
  labs(title = " test set - front bogie - z motion - all points")+
  geom_abline(aes(slope =1, intercept=0.0))


train_data %>% 
  ggplot(.,aes(x = 1.5*azp_fl_2-0.5*azp_fr_2, 
               y = 1.5*az_1l_2-0.5*az_1r_2+1.5*az_2l_2-0.5*az_2r_2, color=as.factor(Speed)))+geom_point()+
  labs(title = " train set - front bogie - roll")+
  geom_abline(aes(slope =1, intercept=0.0))

test_data %>% 
  ggplot(.,aes(x = 1.5*azp_fl_2-0.5*azp_fr_2, 
               y = 1.5*az_1l_2-0.5*az_1r_2+1.5*az_2l_2-0.5*az_2r_2, color=as.factor(Speed)))+geom_point()+
  labs(title = " test set - front bogie - roll")+
  geom_abline(aes(slope =1, intercept=0.0))


train_data %>%
  ggplot(.,aes(x=1.5*azp_1_2-0.5*azp_2_2, 
               y=1.5*az_1l_2+1.5*az_1r_2-0.5*az_2l_2-0.5*az_2r_2, color=as.factor(Speed)))+geom_point()+
  labs(title = " train set - front bogie - pitch - all points")+
  geom_abline(aes(slope =1, intercept=0.0))

test_data %>% 
  ggplot(.,aes(x = 1.5*azp_1_2-0.5*azp_2_2, 
               y = 1.5*az_1l_2+1.5*az_1r_2-0.5*az_2l_2-0.5*az_2r_2, color=as.factor(Speed)))+geom_point()+
  labs(title = " test set - front bogie - pitch - all points")+
  geom_abline(aes(slope =1, intercept=0.0))

#z motion distribution

train_data %>% 
  ggplot(.,aes(x=(azp_1_2+azp_2_2)/(az_1r_2+az_1l_2+az_2l_2+az_2r_2), fill=as.factor(Speed)))+geom_histogram()+
  labs(title = " train set - front bogie - z motion - all points")+
  geom_abline(aes(slope =1, intercept=0.0))


test_data %>% 
  ggplot(.,aes(x=(azp_1_2+azp_2_2)/(az_1r_2+az_1l_2+az_2l_2+az_2r_2), fill=as.factor(Speed)))+geom_histogram()+
  labs(title = " test set - front bogie - z motion - all points")+
  geom_abline(aes(slope =1, intercept=0.0))


#z motion - front bogie
train_data %>% 
  ggplot(.,aes(x=azp_1_2+azp_2_2, 
               y=1.5*azp_1_2-0.5*azp_2_2, color=Payload))+
  geom_point()+
  labs(title = " train set - front bogie -pitch vs. z motion - all points")+
  geom_abline(aes(slope =1, intercept=0.0))

test_data %>% 
  ggplot(.,aes(x=azp_1_2+azp_2_2, 
               y=1.5*azp_1_2-0.5*azp_2_2, color=Payload))+
  geom_point()+
  labs(title = " test set - front bogie - pitch vs. z motion - all points")+
  geom_abline(aes(slope =1, intercept=0.0))

train_data %>% 
  ggplot(.,aes(x=azp_1_2+azp_2_2, 
               y=1.5*azp_fl_2-0.5*azp_fr_2, color=as.factor(Speed)))+
  geom_point()+
  labs(title = " train set - front bogie -roll vs. z motion - all points")+
  geom_abline(aes(slope =1, intercept=0.0))

test_data %>% 
  ggplot(.,aes(x=azp_1_2+azp_2_2, 
               y=1.5*azp_fl_2-0.5*azp_fr_2, color=as.factor(Speed)))+
  geom_point()+
  labs(title = " test set - front bogie - roll vs. z motion - all points")+
  geom_abline(aes(slope =1, intercept=0.0))

#z motion - front bogie

train_data %>% filter(lp<120 & lp>100) %>%
  ggplot(.,aes(x=azp_1_2+azp_2_2, y=az_1r_2+az_1l_2+az_2l_2+az_2r_2, color=as.factor(Speed)))+geom_point()+
  facet_wrap(~lp)+
  labs(title = " train set - front bogie - z motion")+
  geom_abline(aes(slope =1, intercept=0.0))

#roll motion - front bogie

train_data %>% filter(lp<120 & lp>100) %>%
  ggplot(.,aes(x=1.5*azp_fl_2-0.5*azp_fr_2, 
               y=1.5*az_1l_2-0.5*az_1r_2+1.5*az_2l_2-0.5*az_2r_2, color=as.factor(Speed)))+geom_point()+
  facet_wrap(~lp)+
  labs(title = " train set - front bogie - roll")+
  geom_abline(aes(slope =1, intercept=0.0))

# pitch motion - front bogie

train_data %>% filter(lp<120 & lp>100) %>%
  ggplot(.,aes(x=1.5*azp_1_2-0.5*azp_2_2, 
               y=1.5*az_1l_2+1.5*az_1r_2-0.5*az_2l_2-0.5*az_2r_2, color=as.factor(Speed)))+geom_point()+
  facet_wrap(~lp)+
  labs(title = " train set - front bogie - pitch")+
  geom_abline(aes(slope =1, intercept=0.0))


# same on test set
# z motion
test_data %>% filter(lp_off<120 &lp_off>100) %>%
  ggplot(.,aes(x=azp_1_2+azp_2_2, y=az_1r_2+az_1l_2+az_2l_2+az_2r_2, color=as.factor(Speed)))+geom_point()+
  facet_wrap(~lp_off)+
  labs(title = " test set - front bogie - z motion")+
  geom_abline(aes(slope =1, intercept=0.0))

# roll
test_data %>% filter(lp_off<120 &lp_off>100) %>%
  ggplot(.,aes(x=1.5*azp_fl_2-0.5*azp_fr_2, 
               y=1.5*az_1l_2-0.5*az_1r_2+1.5*az_2l_2-0.5*az_2r_2, color=as.factor(Speed)))+geom_point()+
  facet_wrap(~lp_off)+
  labs(title = " test set - front bogie - roll")+
  geom_abline(aes(slope =1, intercept=0.0))

# pitch
test_data %>% filter(lp_off<120 &lp_off>100) %>%
  ggplot(.,aes(x=1.5*azp_1_2-0.5*azp_fr_2, 
               y=1.5*az_1l_2+1.5*az_1r_2-0.5*az_2l_2-0.5*az_2r_2, color=as.factor(Speed)))+geom_point()+
  facet_wrap(~lp_off)+
  labs(title = " test set - front bogie - pitch")+
  geom_abline(aes(slope =1, intercept=0.0))


```
   
### Summary stats  

```{r stats1}

train_stats <- train_data %>% 
  group_by(lp,Speed) %>% 
  summarise(med_azp_f_2 = median(azp_1_2+azp_2_2),
            stdev_azp_f_2 = sd(azp_1_2+azp_2_2),
            med_azp_1_2 = median(azp_1_2),
            stdev_azp_1_2 = sd(azp_1_2))

test_stats <- test_data %>% 
  group_by(lp_off,Speed) %>% 
  summarise(med_azp_f_2 = median(azp_1_2+azp_2_2),
            stdev_azp_f_2 = sd(azp_1_2+azp_2_2),
            med_azp_1_2 = median(azp_1_2),
            stdev_azp_1_2 = sd(azp_1_2))


train_stats %>% ggplot(aes(x=stdev_azp_f_2,fill=as.factor(Speed)))+geom_histogram()

test_stats %>% ggplot(aes(x=stdev_azp_f_2,fill = as.factor(Speed)))+geom_histogram()

train_stats %>% ggplot(aes(x=med_azp_f_2,fill=as.factor(Speed)))+geom_histogram()

test_stats %>% ggplot(aes(x=med_azp_f_2,fill = as.factor(Speed)))+geom_histogram()


train_stats %>% ggplot(aes(x=med_azp_1_2,fill=as.factor(Speed)))+geom_histogram()

test_stats %>% ggplot(aes(x=med_azp_1_2,fill = as.factor(Speed)))+geom_histogram()

train_stats %>% ggplot(aes(x=stdev_azp_1_2,fill=as.factor(Speed)))+geom_histogram()

test_stats %>% ggplot(aes(x=stdev_azp_1_2,fill = as.factor(Speed)))+geom_histogram()

```

## example springs

```{r example springs}

test_data %>% filter(ExperimentID==1) %>%
  ggplot(.)+
  geom_line(aes(x=lp,y=b1z_1),color="red")+
  geom_point(aes(x=lp,y=b1z_1),color="red")+
  geom_line(aes(x=lp,y=b1z_1_pred),color="green")+
  geom_point(aes(x=lp,y=b1z_1_pred),color="green")

test_data %>% filter(ExperimentID==168) %>%
  ggplot(.)+
  geom_line(aes(x=lp,y=b1z_1),color="red")+
  geom_point(aes(x=lp,y=b1z_1),color="red")+
  geom_line(aes(x=lp,y=b1z_1_pred),color="green")+
  geom_point(aes(x=lp,y=b1z_1_pred),color="green")

test_data %>% filter(ExperimentID==1) %>%
  ggplot(.)+
  geom_line(aes(x=lp,y=b1p_3),color="red")+
  geom_point(aes(x=lp,y=b1p_3),color="red")+
  geom_line(aes(x=lp,y=b1p_3_pred),color="green")+
  geom_point(aes(x=lp,y=b1p_3_pred),color="green")
test_data %>% filter(ExperimentID==168) %>%
  ggplot(.)+
  geom_line(aes(x=lp,y=b1p_3),color="red")+
  geom_point(aes(x=lp,y=b1p_3),color="red")+
  geom_line(aes(x=lp,y=b1p_3_pred),color="green")+
  geom_point(aes(x=lp,y=b1p_3_pred),color="green")

```

```{r Review past submission}
# spirings_s %>% filter(State != "healthy" ) %>% select(-State)
Exp_sel <- spirings_s %>% filter(State != "healthy"  & grepl("1$",State)) %>% select(-State) 
names(test_data)
test_data %>% right_join(Exp_sel )  %>%
  ggplot(.)+
  geom_histogram(aes(x=pz_1_res),alpha=0.5,fill="blue")+
  geom_histogram(aes(x=pz_2_res),alpha=0.5,fill="red")+
  geom_histogram(aes(x=pz_3_res),alpha=0.5,fill="green")+
  geom_histogram(aes(x=pz_4_res),alpha=0.5,fill="orange")+
  geom_histogram(aes(x=pz_5_res),alpha=0.5,fill="purple")+
  geom_vline(xintercept=0.0)+
  facet_wrap(~ExperimentID)

Exp_sel <- spirings_s %>% filter(State != "healthy"  & grepl("1$",State)) %>% select(-State) 
test_data %>% right_join(Exp_sel )  %>%
  ggplot(.)+
  geom_histogram(aes(x=pp_1_res),alpha=0.5,fill="blue")+
  geom_histogram(aes(x=pp_2_res),alpha=0.5,fill="red")+
  geom_histogram(aes(x=pp_3_res),alpha=0.5,fill="green")+
  geom_histogram(aes(x=pp_4_res),alpha=0.5,fill="orange")+
  geom_histogram(aes(x=pp_5_res),alpha=0.5,fill="purple")+
  geom_vline(xintercept=0.0)+
  facet_wrap(~ExperimentID)


```

```{r Springs}
# spirings_s %>% filter(State != "healthy" ) %>% select(-State)
# Exp_sel <- spirings_s %>% filter(State != "healthy"  & grepl("1$",State)) %>% select(-State) 
# names(test_data)
test_data_summ %>%
  ggplot(.)+
  geom_point(aes(x = pz_1_res_median, y = ExperimentID ,color = "1"),alpha=0.5)+
  geom_point(aes(x = pz_2_res_median, y = ExperimentID ,color = "2"),alpha=0.5)+
  geom_point(aes(x = pz_3_res_median, y = ExperimentID ,color = "3"),alpha=0.5)+
  # geom_point(aes(x = pz_4_res_median, y = ExperimentID ,color = "4"),alpha=0.5)+
  # geom_point(aes(x = pz_5_res_median, y = ExperimentID ,color = "5"),alpha=0.5)+
  geom_vline(xintercept = 0.0) +
    geom_vline(xintercept = -0.03) +
    geom_vline(xintercept = 0.02)

train_data_summ %>%
  ggplot(.)+
  geom_point(aes(x = pz_1_res_median, y = ExperimentID ,color = "1"),alpha=0.5)+
  geom_point(aes(x = pz_2_res_median, y = ExperimentID ,color = "2"),alpha=0.5)+
  geom_point(aes(x = pz_3_res_median, y = ExperimentID ,color = "3"),alpha=0.5)+
  # geom_point(aes(x = pz_4_res_median, y = ExperimentID ,color = "4"),alpha=0.5)+
  # geom_point(aes(x = pz_5_res_median, y = ExperimentID ,color = "5"),alpha=0.5)+
  geom_vline(xintercept = 0.0) +
    geom_vline(xintercept = -0.03) +
    geom_vline(xintercept = 0.02)


test_data_summ %>%
  ggplot(.)+
  geom_point(aes(x = pp_1_res_median, y = ExperimentID ,color = "1"),alpha=0.5)+
  geom_point(aes(x = pp_2_res_median, y = ExperimentID ,color = "2"),alpha=0.5)+
  geom_point(aes(x = pp_3_res_median, y = ExperimentID ,color = "3"),alpha=0.5)+
  # geom_point(aes(x = pp_4_res_median, y = ExperimentID ,color = "4"),alpha=0.5)+
  # geom_point(aes(x = pp_5_res_median, y = ExperimentID ,color = "5"),alpha=0.5)+
  geom_vline(xintercept = 0.0) +
    geom_vline(xintercept = -0.03) +
    geom_vline(xintercept = 0.02)

train_data_summ %>%
  ggplot(.)+
  geom_point(aes(x = pp_1_res_median, y = ExperimentID ,color = "1"),alpha=0.5)+
  geom_point(aes(x = pp_2_res_median, y = ExperimentID ,color = "2"),alpha=0.5)+
  geom_point(aes(x = pp_3_res_median, y = ExperimentID ,color = "3"),alpha=0.5)+
  # geom_point(aes(x = pp_4_res_median, y = ExperimentID ,color = "4"),alpha=0.5)+
  # geom_point(aes(x = pp_5_res_median, y = ExperimentID ,color = "5"),alpha=0.5)+
  geom_vline(xintercept = 0.0) +
    geom_vline(xintercept = -0.03) +
    geom_vline(xintercept = 0.02)

#
# bogie
#
test_data_summ %>%
  ggplot(.)+
  geom_point(aes(x = b1z_1_res_median, y = ExperimentID ,color = "1"),alpha=0.5)+
  geom_point(aes(x = b1z_2_res_median, y = ExperimentID ,color = "2"),alpha=0.5)+
  geom_point(aes(x = b1z_3_res_median, y = ExperimentID ,color = "3"),alpha=0.5)+
  # geom_point(aes(x = b1z_4_res_median, y = ExperimentID ,color = "4"),alpha=0.5)+
  # geom_point(aes(x = b1z_5_res_median, y = ExperimentID ,color = "5"),alpha=0.5)+
  geom_vline(xintercept = 0.0) +
    geom_vline(xintercept = -0.03) +
    geom_vline(xintercept = 0.02)

train_data_summ %>%
  ggplot(.)+
  geom_point(aes(x = b1z_1_res_median, y = ExperimentID ,color = "1"),alpha=0.5)+
  geom_point(aes(x = b1z_2_res_median, y = ExperimentID ,color = "2"),alpha=0.5)+
  geom_point(aes(x = b1z_3_res_median, y = ExperimentID ,color = "3"),alpha=0.5)+
  # geom_point(aes(x = b1z_4_res_median, y = ExperimentID ,color = "4"),alpha=0.5)+
  # geom_point(aes(x = b1z_5_res_median, y = ExperimentID ,color = "5"),alpha=0.5)+
  geom_vline(xintercept = 0.0) +
    geom_vline(xintercept = -0.03) +
    geom_vline(xintercept = 0.02)


test_data_summ %>%
  ggplot(.)+
  geom_point(aes(x = b1r_1_res_median, y = ExperimentID ,color = "1"),alpha=0.5)+
  geom_point(aes(x = b1r_2_res_median, y = ExperimentID ,color = "2"),alpha=0.5)+
  geom_point(aes(x = b1r_3_res_median, y = ExperimentID ,color = "3"),alpha=0.5)+
  geom_point(aes(x = b1r_4_res_median, y = ExperimentID ,color = "4"),alpha=0.5)+
  geom_point(aes(x = b1r_5_res_median, y = ExperimentID ,color = "5"),alpha=0.5)+
  geom_vline(xintercept = 0.0) +
    geom_vline(xintercept = -0.03) +
    geom_vline(xintercept = 0.02)

train_data_summ %>%
  ggplot(.)+
  geom_point(aes(x = b1r_1_res_median, y = ExperimentID ,color = "1"),alpha=0.5)+
  geom_point(aes(x = b1r_2_res_median, y = ExperimentID ,color = "2"),alpha=0.5)+
  geom_point(aes(x = b1r_3_res_median, y = ExperimentID ,color = "3"),alpha=0.5)+
  geom_point(aes(x = b1r_4_res_median, y = ExperimentID ,color = "4"),alpha=0.5)+
  geom_point(aes(x = b1r_5_res_median, y = ExperimentID ,color = "5"),alpha=0.5)+
  geom_vline(xintercept = 0.0) +
    geom_vline(xintercept = -0.03) +
    geom_vline(xintercept = 0.02)



#
# Residuals might not be very informative?
#
# 
# test_data_summ %>%
#   ggplot(.)+
#   geom_point(aes(x = pz_1_res_sd, y = ExperimentID ,color = "1"),alpha=0.5)+
#   geom_point(aes(x = pz_2_res_sd, y = ExperimentID ,color = "2"),alpha=0.5)+
#   geom_point(aes(x = pz_3_res_sd, y = ExperimentID ,color = "3"),alpha=0.5)+
#   geom_point(aes(x = pz_4_res_sd, y = ExperimentID ,color = "4"),alpha=0.5)+
#   geom_point(aes(x = pz_5_res_sd, y = ExperimentID ,color = "5"),alpha=0.5)+
#   geom_vline(xintercept = 0.0) +
#     geom_vline(xintercept = -0.03) +
#     geom_vline(xintercept = 0.02)
# 
# train_data_summ %>%
#   ggplot(.)+
#   geom_point(aes(x = pz_1_res_sd, y = ExperimentID ,color = "1"),alpha=0.5)+
#   geom_point(aes(x = pz_2_res_sd, y = ExperimentID ,color = "2"),alpha=0.5)+
#   geom_point(aes(x = pz_3_res_sd, y = ExperimentID ,color = "3"),alpha=0.5)+
#   geom_point(aes(x = pz_4_res_sd, y = ExperimentID ,color = "4"),alpha=0.5)+
#   geom_point(aes(x = pz_5_res_sd, y = ExperimentID ,color = "5"),alpha=0.5)+
#   geom_vline(xintercept = 0.0) +
#     geom_vline(xintercept = -0.03) +
#     geom_vline(xintercept = 0.02)
# 
# test_data_summ %>%
#   ggplot(.)+
#   geom_point(aes(x = pp_1_res_sd, y = ExperimentID ,color = "1"),alpha=0.5)+
#   geom_point(aes(x = pp_2_res_sd, y = ExperimentID ,color = "2"),alpha=0.5)+
#   geom_point(aes(x = pp_3_res_sd, y = ExperimentID ,color = "3"),alpha=0.5)+
#   geom_point(aes(x = pp_4_res_sd, y = ExperimentID ,color = "4"),alpha=0.5)+
#   geom_point(aes(x = pp_5_res_sd, y = ExperimentID ,color = "5"),alpha=0.5)+
#   geom_vline(xintercept = 0.0) +
#     geom_vline(xintercept = -0.03) +
#     geom_vline(xintercept = 0.02)
# 
# train_data_summ %>%
#   ggplot(.)+
#   geom_point(aes(x = pp_1_res_sd, y = ExperimentID ,color = "1"),alpha=0.5)+
#   geom_point(aes(x = pp_2_res_sd, y = ExperimentID ,color = "2"),alpha=0.5)+
#   geom_point(aes(x = pp_3_res_sd, y = ExperimentID ,color = "3"),alpha=0.5)+
#   geom_point(aes(x = pp_4_res_sd, y = ExperimentID ,color = "4"),alpha=0.5)+
#   geom_point(aes(x = pp_5_res_sd, y = ExperimentID ,color = "5"),alpha=0.5)+
#   geom_vline(xintercept = 0.0) +
#     geom_vline(xintercept = -0.03) +
#     geom_vline(xintercept = 0.02)

```



## Treshold look up with Medians

```{r thesholds with medians bogie}

# some crazy thresholds (for standardized residual values)
# establishing thresholds based on training median
th_b1p_1_low = min(train_data_summ$b1p_1_res_median)
th_b1p_2_low = min(train_data_summ$b1p_2_res_median)
th_b1p_3_low = min(train_data_summ$b1p_3_res_median)
th_b1p_4_low = min(train_data_summ$b1p_4_res_median)
th_b1p_5_low = min(train_data_summ$b1p_5_res_median)

th_b1z_1_low = min(train_data_summ$b1z_1_res_median)
th_b1z_2_low = min(train_data_summ$b1z_2_res_median)
th_b1z_3_low = min(train_data_summ$b1z_3_res_median)
th_b1z_4_low = min(train_data_summ$b1z_4_res_median)
th_b1z_5_low = min(train_data_summ$b1z_5_res_median)

th_b1r_1_low = min(train_data_summ$b1r_1_res_median)
th_b1r_2_low = min(train_data_summ$b1r_2_res_median)
th_b1r_3_low = min(train_data_summ$b1r_3_res_median)
th_b1r_4_low = min(train_data_summ$b1r_4_res_median)
th_b1r_5_low = min(train_data_summ$b1r_5_res_median)


th_b1p_1_high = max(train_data_summ$b1p_1_res_median)
th_b1p_2_high = max(train_data_summ$b1p_2_res_median)
th_b1p_3_high = max(train_data_summ$b1p_3_res_median)
th_b1p_4_high = max(train_data_summ$b1p_4_res_median)
th_b1p_5_high = max(train_data_summ$b1p_5_res_median)

th_b1z_1_high = max(train_data_summ$b1z_1_res_median)
th_b1z_2_high = max(train_data_summ$b1z_2_res_median)
th_b1z_3_high = max(train_data_summ$b1z_3_res_median)
th_b1z_4_high = max(train_data_summ$b1z_4_res_median)
th_b1z_5_high = max(train_data_summ$b1z_5_res_median)

th_b1r_1_high = max(train_data_summ$b1r_1_res_median)
th_b1r_2_high = max(train_data_summ$b1r_2_res_median)
th_b1r_3_high = max(train_data_summ$b1r_3_res_median)
th_b1r_4_high = max(train_data_summ$b1r_4_res_median)
th_b1r_5_high = max(train_data_summ$b1r_5_res_median)

th_b2p_1_low = min(train_data_summ$b2p_1_res_median)
th_b2p_2_low = min(train_data_summ$b2p_2_res_median)
th_b2p_3_low = min(train_data_summ$b2p_3_res_median)
th_b2p_4_low = min(train_data_summ$b2p_4_res_median)
th_b2p_5_low = min(train_data_summ$b2p_5_res_median)

th_b2z_1_low = min(train_data_summ$b2z_1_res_median)
th_b2z_2_low = min(train_data_summ$b2z_2_res_median)
th_b2z_3_low = min(train_data_summ$b2z_3_res_median)
th_b2z_4_low = min(train_data_summ$b2z_4_res_median)
th_b2z_5_low = min(train_data_summ$b2z_5_res_median)

th_b2r_1_low = min(train_data_summ$b2r_1_res_median)
th_b2r_2_low = min(train_data_summ$b2r_2_res_median)
th_b2r_3_low = min(train_data_summ$b2r_3_res_median)
th_b2r_4_low = min(train_data_summ$b2r_4_res_median)
th_b2r_5_low = min(train_data_summ$b2r_5_res_median)


th_b2p_1_high = max(train_data_summ$b2p_1_res_median)
th_b2p_2_high = max(train_data_summ$b2p_2_res_median)
th_b2p_3_high = max(train_data_summ$b2p_3_res_median)
th_b2p_4_high = max(train_data_summ$b2p_4_res_median)
th_b2p_5_high = max(train_data_summ$b2p_5_res_median)

th_b2z_1_high = max(train_data_summ$b2z_1_res_median)
th_b2z_2_high = max(train_data_summ$b2z_2_res_median)
th_b2z_3_high = max(train_data_summ$b2z_3_res_median)
th_b2z_4_high = max(train_data_summ$b2z_4_res_median)
th_b2z_5_high = max(train_data_summ$b2z_5_res_median)

th_b2r_1_high = max(train_data_summ$b2r_1_res_median)
th_b2r_2_high = max(train_data_summ$b2r_2_res_median)
th_b2r_3_high = max(train_data_summ$b2r_3_res_median)
th_b2r_4_high = max(train_data_summ$b2r_4_res_median)
th_b2r_5_high = max(train_data_summ$b2r_5_res_median)

# sd calc
th_b1p_1_sd = sd(train_data_summ$b1p_1_res_median)
th_b1p_2_sd = sd(train_data_summ$b1p_2_res_median)
th_b1p_3_sd = sd(train_data_summ$b1p_3_res_median)
th_b1p_4_sd = sd(train_data_summ$b1p_4_res_median)
th_b1p_5_sd = sd(train_data_summ$b1p_5_res_median)

th_b1z_1_sd = sd(train_data_summ$b1z_1_res_median)
th_b1z_2_sd = sd(train_data_summ$b1z_2_res_median)
th_b1z_3_sd = sd(train_data_summ$b1z_3_res_median)
th_b1z_4_sd = sd(train_data_summ$b1z_4_res_median)
th_b1z_5_sd = sd(train_data_summ$b1z_5_res_median)

th_b1r_1_sd = sd(train_data_summ$b1r_1_res_median)
th_b1r_2_sd = sd(train_data_summ$b1r_2_res_median)
th_b1r_3_sd = sd(train_data_summ$b1r_3_res_median)
th_b1r_4_sd = sd(train_data_summ$b1r_4_res_median)
th_b1r_5_sd = sd(train_data_summ$b1r_5_res_median)

th_b2p_1_sd = sd(train_data_summ$b2p_1_res_median)
th_b2p_2_sd = sd(train_data_summ$b2p_2_res_median)
th_b2p_3_sd = sd(train_data_summ$b2p_3_res_median)
th_b2p_4_sd = sd(train_data_summ$b2p_4_res_median)
th_b2p_5_sd = sd(train_data_summ$b2p_5_res_median)

th_b2z_1_sd = sd(train_data_summ$b2z_1_res_median)
th_b2z_2_sd = sd(train_data_summ$b2z_2_res_median)
th_b2z_3_sd = sd(train_data_summ$b2z_3_res_median)
th_b2z_4_sd = sd(train_data_summ$b2z_4_res_median)
th_b2z_5_sd = sd(train_data_summ$b2z_5_res_median)

th_b2r_1_sd = sd(train_data_summ$b2r_1_res_median)
th_b2r_2_sd = sd(train_data_summ$b2r_2_res_median)
th_b2r_3_sd = sd(train_data_summ$b2r_3_res_median)
th_b2r_4_sd = sd(train_data_summ$b2r_4_res_median)
th_b2r_5_sd = sd(train_data_summ$b2r_5_res_median)


test_data_summ %>% 
  filter(th_b1z_1_low - th_b1z_1_sd > b1z_1_res_median | b1z_1_res_median > th_b1z_1_high + th_b1z_1_sd |
         # th_b1z_4_low - th_b1z_4_sd > b1z_4_res_median | b1z_4_res_median > th_b1z_4_high + th_b1z_4_sd |
         th_b1z_3_low - th_b1z_3_sd > b1z_3_res_median | b1z_3_res_median > th_b1z_3_high + th_b1z_3_sd |
         th_b1z_2_low - th_b1z_2_sd > b1z_2_res_median | b1z_2_res_median > th_b1z_2_high + th_b1z_2_sd |
         th_b2z_1_low - th_b2z_1_sd > b2z_1_res_median | b2z_1_res_median > th_b2z_1_high + th_b2z_1_sd |
         th_b2z_3_low - th_b2z_3_sd > b2z_3_res_median | b2z_3_res_median > th_b2z_3_high + th_b2z_3_sd |
         th_b2z_2_low - th_b2z_2_sd > b2z_2_res_median | b2z_2_res_median > th_b2z_2_high + th_b2z_2_sd #|
         # th_b2z_4_low - th_b2z_4_sd > b2z_4_res_median | b2z_4_res_median > th_b2z_4_high + th_b2z_4_sd
         ) %>%
  # count()
select(ExperimentID)


```


## Platform


```{r thesholds with medians paltform}

# some crazy thresholds (for standardized residual values)
# establishing thresholds based on training median
th_pp_1_low = min(train_data_summ$pp_1_res_median)
th_pp_2_low = min(train_data_summ$pp_2_res_median)
th_pp_3_low = min(train_data_summ$pp_3_res_median)
th_pp_4_low = min(train_data_summ$pp_4_res_median)
th_pp_5_low = min(train_data_summ$pp_5_res_median)

th_pz_1_low = min(train_data_summ$pz_1_res_median)
th_pz_2_low = min(train_data_summ$pz_2_res_median)
th_pz_3_low = min(train_data_summ$pz_3_res_median)
th_pz_4_low = min(train_data_summ$pz_4_res_median)
th_pz_5_low = min(train_data_summ$pz_5_res_median)


th_pp_1_high = max(train_data_summ$pp_1_res_median)
th_pp_2_high = max(train_data_summ$pp_2_res_median)
th_pp_3_high = max(train_data_summ$pp_3_res_median)
th_pp_4_high = max(train_data_summ$pp_4_res_median)
th_pp_5_high = max(train_data_summ$pp_5_res_median)

th_pz_1_high = max(train_data_summ$pz_1_res_median)
th_pz_2_high = max(train_data_summ$pz_2_res_median)
th_pz_3_high = max(train_data_summ$pz_3_res_median)
th_pz_4_high = max(train_data_summ$pz_4_res_median)
th_pz_5_high = max(train_data_summ$pz_5_res_median)

# sd calc
th_pp_1_sd = sd(train_data_summ$pp_1_res_median)
th_pp_2_sd = sd(train_data_summ$pp_2_res_median)
th_pp_3_sd = sd(train_data_summ$pp_3_res_median)
th_pp_4_sd = sd(train_data_summ$pp_4_res_median)
th_pp_5_sd = sd(train_data_summ$pp_5_res_median)

th_pz_1_sd = sd(train_data_summ$pz_1_res_median)
th_pz_2_sd = sd(train_data_summ$pz_2_res_median)
th_pz_3_sd = sd(train_data_summ$pz_3_res_median)
th_pz_4_sd = sd(train_data_summ$pz_4_res_median)
th_pz_5_sd = sd(train_data_summ$pz_5_res_median)


test_data_summ %>% 
  filter(
        # th_pz_1_low - th_pz_1_sd*3 > pz_1_res_median | pz_1_res_median > th_pz_1_high + th_pz_1_sd*3 |
        # th_pz_4_low - th_pz_4_sd*3 > pz_4_res_median | pz_4_res_median > th_pz_4_high + th_pz_4_sd*3 |
        # th_pz_3_low - th_pz_3_sd*3 > pz_3_res_median | pz_3_res_median > th_pz_3_high + th_pz_3_sd*3 |
        # th_pz_2_low - th_pz_2_sd*3 > pz_2_res_median | pz_2_res_median > th_pz_2_high + th_pz_2_sd*3 |
        th_pp_1_low - th_pp_1_sd*3 > pp_1_res_median | pp_1_res_median > th_pp_1_high + th_pp_1_sd*3 #|
        # th_pp_3_low - th_pp_3_sd*3 > pp_3_res_median | pp_3_res_median > th_pp_3_high + th_pp_3_sd*3 |
        # th_pp_2_low - th_pp_2_sd*3 > pp_2_res_median | pp_2_res_median > th_pp_2_high + th_pp_2_sd*3 #|
        # th_pp_4_low - th_pp_4_sd*3 > pp_4_res_median | pp_4_res_median > th_pp_4_high + th_pp_4_sd*3
         ) %>%
  # count()
select(ExperimentID)


```

## thershods percentiles q25 q75

```{r thesholds with medians}

# q25 low and Q75 high


th_b1p_1_low = min(train_data_summ$b1p_1_res_q25)
th_b1p_2_low = min(train_data_summ$b1p_2_res_q25)
th_b1p_3_low = min(train_data_summ$b1p_3_res_q25)
th_b1p_4_low = min(train_data_summ$b1p_4_res_q25)
th_b1p_5_low = min(train_data_summ$b1p_5_res_q25)

th_b1z_1_low = min(train_data_summ$b1z_1_res_q25)
th_b1z_2_low = min(train_data_summ$b1z_2_res_q25)
th_b1z_3_low = min(train_data_summ$b1z_3_res_q25)
th_b1z_4_low = min(train_data_summ$b1z_4_res_q25)
th_b1z_5_low = min(train_data_summ$b1z_5_res_q25)

th_b1r_1_low = min(train_data_summ$b1r_1_res_q25)
th_b1r_2_low = min(train_data_summ$b1r_2_res_q25)
th_b1r_3_low = min(train_data_summ$b1r_3_res_q25)
th_b1r_4_low = min(train_data_summ$b1r_4_res_q25)
th_b1r_5_low = min(train_data_summ$b1r_5_res_q25)


th_b1p_1_high = max(train_data_summ$b1p_1_res_q75)
th_b1p_2_high = max(train_data_summ$b1p_2_res_q75)
th_b1p_3_high = max(train_data_summ$b1p_3_res_q75)
th_b1p_4_high = max(train_data_summ$b1p_4_res_q75)
th_b1p_5_high = max(train_data_summ$b1p_5_res_q75)

th_b1z_1_high = max(train_data_summ$b1z_1_res_q75)
th_b1z_2_high = max(train_data_summ$b1z_2_res_q75)
th_b1z_3_high = max(train_data_summ$b1z_3_res_q75)
th_b1z_4_high = max(train_data_summ$b1z_4_res_q75)
th_b1z_5_high = max(train_data_summ$b1z_5_res_q75)

th_b1r_1_high = max(train_data_summ$b1r_1_res_q75)
th_b1r_2_high = max(train_data_summ$b1r_2_res_q75)
th_b1r_3_high = max(train_data_summ$b1r_3_res_q75)
th_b1r_4_high = max(train_data_summ$b1r_4_res_q75)
th_b1r_5_high = max(train_data_summ$b1r_5_res_q75)

th_b2p_1_low = min(train_data_summ$b2p_1_res_q25)
th_b2p_2_low = min(train_data_summ$b2p_2_res_q25)
th_b2p_3_low = min(train_data_summ$b2p_3_res_q25)
th_b2p_4_low = min(train_data_summ$b2p_4_res_q25)
th_b2p_5_low = min(train_data_summ$b2p_5_res_q25)

th_b2z_1_low = min(train_data_summ$b2z_1_res_q25)
th_b2z_2_low = min(train_data_summ$b2z_2_res_q25)
th_b2z_3_low = min(train_data_summ$b2z_3_res_q25)
th_b2z_4_low = min(train_data_summ$b2z_4_res_q25)
th_b2z_5_low = min(train_data_summ$b2z_5_res_q25)

th_b2r_1_low = min(train_data_summ$b2r_1_res_q25)
th_b2r_2_low = min(train_data_summ$b2r_2_res_q25)
th_b2r_3_low = min(train_data_summ$b2r_3_res_q25)
th_b2r_4_low = min(train_data_summ$b2r_4_res_q25)
th_b2r_5_low = min(train_data_summ$b2r_5_res_q25)


th_b2p_1_high = max(train_data_summ$b2p_1_res_q75)
th_b2p_2_high = max(train_data_summ$b2p_2_res_q75)
th_b2p_3_high = max(train_data_summ$b2p_3_res_q75)
th_b2p_4_high = max(train_data_summ$b2p_4_res_q75)
th_b2p_5_high = max(train_data_summ$b2p_5_res_q75)

th_b2z_1_high = max(train_data_summ$b2z_1_res_q75)
th_b2z_2_high = max(train_data_summ$b2z_2_res_q75)
th_b2z_3_high = max(train_data_summ$b2z_3_res_q75)
th_b2z_4_high = max(train_data_summ$b2z_4_res_q75)
th_b2z_5_high = max(train_data_summ$b2z_5_res_q75)

th_b2r_1_high = max(train_data_summ$b2r_1_res_q75)
th_b2r_2_high = max(train_data_summ$b2r_2_res_q75)
th_b2r_3_high = max(train_data_summ$b2r_3_res_q75)
th_b2r_4_high = max(train_data_summ$b2r_4_res_q75)
th_b2r_5_high = max(train_data_summ$b2r_5_res_q75)


test_data_summ %>%
  ggplot(.)+
  geom_histogram(aes(x=b1z_4_res_q25))+
  geom_vline(xintercept = th_b1z_4_low)+
  geom_vline(xintercept = 1.1*th_b1z_4_low,color="red")+
  geom_vline(xintercept = th_b1z_4_high)+
  geom_vline(xintercept = 1.1*th_b1z_4_high,color="red")
  


test_data_summ %>% 
  filter(1.05*th_b1z_4_low > b1z_4_res_q25 | b1z_4_res_q75 > 1.05*th_b1z_4_high |
         1.05*th_b1z_3_low > b1z_3_res_q25 | b1z_3_res_q75 > 1.05*th_b1z_3_high |
         1.05*th_b1z_2_low > b1z_2_res_q25 | b1z_2_res_q75 > 1.05*th_b1z_2_high |
         1.05*th_b1z_1_low > b1z_1_res_q25 | b1z_1_res_q75 > 1.05*th_b1z_1_high |
         1.05*th_b2z_3_low > b2z_3_res_q25 | b2z_3_res_q75 > 1.05*th_b2z_3_high |
         1.05*th_b2z_2_low > b2z_2_res_q25 | b2z_2_res_q75 > 1.05*th_b2z_2_high |
         1.05*th_b2z_1_low > b2z_1_res_q25 | b2z_1_res_q75 > 1.05*th_b2z_1_high |
         1.05*th_b2z_4_low > b2z_4_res_q25 | b2z_4_res_q75 > 1.05*th_b2z_4_high) %>%
  count()

test_data_summ %>% 
  filter(1.0*th_b1z_4_low > b1z_4_res_q25 | b1z_4_res_q75 > 1.0*th_b1z_4_high |
         1.0*th_b1z_3_low > b1z_3_res_q25 | b1z_3_res_q75 > 1.0*th_b1z_3_high |
         1.0*th_b1z_2_low > b1z_2_res_q25 | b1z_2_res_q75 > 1.0*th_b1z_2_high |
         1.0*th_b2z_3_low > b2z_3_res_q25 | b2z_3_res_q75 > 1.0*th_b2z_3_high |
         1.0*th_b2z_2_low > b2z_2_res_q25 | b2z_2_res_q75 > 1.0*th_b2z_2_high |
         1.0*th_b2z_4_low > b2z_4_res_q25 | b2z_4_res_q75 > 1.0*th_b2z_4_high) %>%
  count()
```

